package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcAttributeGroupDescriptionId generated by hbm2java
 */
@Embeddable
public class AttributeGroupDescriptionId implements java.io.Serializable {

	private int attributeGroupId;
	private int languageId;

	public AttributeGroupDescriptionId() {
	}

	public AttributeGroupDescriptionId(int attributeGroupId, int languageId) {
		this.attributeGroupId = attributeGroupId;
		this.languageId = languageId;
	}

	@Column(name = "attribute_group_id", nullable = false)
	public int getAttributeGroupId() {
		return this.attributeGroupId;
	}

	public void setAttributeGroupId(int attributeGroupId) {
		this.attributeGroupId = attributeGroupId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttributeGroupDescriptionId))
			return false;
		AttributeGroupDescriptionId castOther = (AttributeGroupDescriptionId) other;

		return (this.getAttributeGroupId() == castOther.getAttributeGroupId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttributeGroupId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
