package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcBannerImageDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_banner_image_description", catalog = "opencart")
public class BannerImageDescription implements java.io.Serializable {

	private BannerImageDescriptionId id;
	private int bannerId;
	private String title;

	public BannerImageDescription() {
	}

	public BannerImageDescription(BannerImageDescriptionId id,
			int bannerId, String title) {
		this.id = id;
		this.bannerId = bannerId;
		this.title = title;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bannerImageId", column = @Column(name = "banner_image_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public BannerImageDescriptionId getId() {
		return this.id;
	}

	public void setId(BannerImageDescriptionId id) {
		this.id = id;
	}

	@Column(name = "banner_id", nullable = false)
	public int getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
