package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcBannerImageDescriptionId generated by hbm2java
 */
@Embeddable
public class BannerImageDescriptionId implements java.io.Serializable {

	private int bannerImageId;
	private int languageId;

	public BannerImageDescriptionId() {
	}

	public BannerImageDescriptionId(int bannerImageId, int languageId) {
		this.bannerImageId = bannerImageId;
		this.languageId = languageId;
	}

	@Column(name = "banner_image_id", nullable = false)
	public int getBannerImageId() {
		return this.bannerImageId;
	}

	public void setBannerImageId(int bannerImageId) {
		this.bannerImageId = bannerImageId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BannerImageDescriptionId))
			return false;
		BannerImageDescriptionId castOther = (BannerImageDescriptionId) other;

		return (this.getBannerImageId() == castOther.getBannerImageId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBannerImageId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
