package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCategoryFilter generated by hbm2java
 */
@Entity
@Table(name = "oc_category_filter", catalog = "opencart")
public class CategoryFilter implements java.io.Serializable {

	private CategoryFilterId id;

	public CategoryFilter() {
	}

	public CategoryFilter(CategoryFilterId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
			@AttributeOverride(name = "filterId", column = @Column(name = "filter_id", nullable = false)) })
	public CategoryFilterId getId() {
		return this.id;
	}

	public void setId(CategoryFilterId id) {
		this.id = id;
	}

}
