package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcCategoryToLayoutId generated by hbm2java
 */
@Embeddable
public class CategoryToLayoutId implements java.io.Serializable {

	private int categoryId;
	private int storeId;

	public CategoryToLayoutId() {
	}

	public CategoryToLayoutId(int categoryId, int storeId) {
		this.categoryId = categoryId;
		this.storeId = storeId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryToLayoutId))
			return false;
		CategoryToLayoutId castOther = (CategoryToLayoutId) other;

		return (this.getCategoryId() == castOther.getCategoryId())
				&& (this.getStoreId() == castOther.getStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryId();
		result = 37 * result + this.getStoreId();
		return result;
	}

}
