package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCategory generated by hbm2java
 */
@Entity
@Table(name = "oc_category", catalog = "opencart")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String image;
	private int parentId;
	private boolean top;
	private int column;
	private int sortOrder;
	private boolean status;
	private Date dateAdded;
	private Date dateModified;
	private Integer externalId;

	public Category() {
	}

	public Category(int parentId, boolean top, int column, int sortOrder,
			boolean status, Date dateAdded, Date dateModified) {
		this.parentId = parentId;
		this.top = top;
		this.column = column;
		this.sortOrder = sortOrder;
		this.status = status;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
	}

	public Category(String image, int parentId, boolean top, int column,
			int sortOrder, boolean status, Date dateAdded, Date dateModified,
			Integer externalId) {
		this.image = image;
		this.parentId = parentId;
		this.top = top;
		this.column = column;
		this.sortOrder = sortOrder;
		this.status = status;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
		this.externalId = externalId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "top", nullable = false)
	public boolean isTop() {
		return this.top;
	}

	public void setTop(boolean top) {
		this.top = top;
	}

	@Column(name = "`column`", nullable = false)
	public int getColumn() {
		return this.column;
	}

	public void setColumn(int column) {
		this.column = column;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "external_id")
	public Integer getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Integer externalId) {
		this.externalId = externalId;
	}

}
