package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCategoryToStore generated by hbm2java
 */
@Entity
@Table(name = "oc_category_to_store", catalog = "opencart")
public class CategoryToStore implements java.io.Serializable {

	private CategoryToStoreId id;

	public CategoryToStore() {
	}

	public CategoryToStore(CategoryToStoreId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
			@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)) })
	public CategoryToStoreId getId() {
		return this.id;
	}

	public void setId(CategoryToStoreId id) {
		this.id = id;
	}

}
