package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCategoryPath generated by hbm2java
 */
@Entity
@Table(name = "oc_category_path", catalog = "opencart")
public class CategoryPath implements java.io.Serializable {

	private CategoryPathId id;
	private int level;

	public CategoryPath() {
	}

	public CategoryPath(CategoryPathId id, int level) {
		this.id = id;
		this.level = level;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)),
			@AttributeOverride(name = "pathId", column = @Column(name = "path_id", nullable = false)) })
	public CategoryPathId getId() {
		return this.id;
	}

	public void setId(CategoryPathId id) {
		this.id = id;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
