package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCouponHistory generated by hbm2java
 */
@Entity
@Table(name = "oc_coupon_history", catalog = "opencart")
public class CouponHistory implements java.io.Serializable {

	private Integer couponHistoryId;
	private int couponId;
	private int orderId;
	private int customerId;
	private BigDecimal amount;
	private Date dateAdded;

	public CouponHistory() {
	}

	public CouponHistory(int couponId, int orderId, int customerId,
			BigDecimal amount, Date dateAdded) {
		this.couponId = couponId;
		this.orderId = orderId;
		this.customerId = customerId;
		this.amount = amount;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coupon_history_id", unique = true, nullable = false)
	public Integer getCouponHistoryId() {
		return this.couponHistoryId;
	}

	public void setCouponHistoryId(Integer couponHistoryId) {
		this.couponHistoryId = couponHistoryId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "amount", nullable = false, precision = 15, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
