package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCouponCategory generated by hbm2java
 */
@Entity
@Table(name = "oc_coupon_category", catalog = "opencart")
public class CouponCategory implements java.io.Serializable {

	private CouponCategoryId id;

	public CouponCategory() {
	}

	public CouponCategory(CouponCategoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)) })
	public CouponCategoryId getId() {
		return this.id;
	}

	public void setId(CouponCategoryId id) {
		this.id = id;
	}

}
