package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcCouponCategoryId generated by hbm2java
 */
@Embeddable
public class CouponCategoryId implements java.io.Serializable {

	private int couponId;
	private int categoryId;

	public CouponCategoryId() {
	}

	public CouponCategoryId(int couponId, int categoryId) {
		this.couponId = couponId;
		this.categoryId = categoryId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CouponCategoryId))
			return false;
		CouponCategoryId castOther = (CouponCategoryId) other;

		return (this.getCouponId() == castOther.getCouponId())
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCouponId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
