package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCurrency generated by hbm2java
 */
@Entity
@Table(name = "oc_currency", catalog = "opencart")
public class Currency implements java.io.Serializable {

	private Integer currencyId;
	private String title;
	private String code;
	private String symbolLeft;
	private String symbolRight;
	private char decimalPlace;
	private float value;
	private boolean status;
	private Date dateModified;

	public Currency() {
	}

	public Currency(String title, String code, String symbolLeft,
			String symbolRight, char decimalPlace, float value, boolean status,
			Date dateModified) {
		this.title = title;
		this.code = code;
		this.symbolLeft = symbolLeft;
		this.symbolRight = symbolRight;
		this.decimalPlace = decimalPlace;
		this.value = value;
		this.status = status;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "currency_id", unique = true, nullable = false)
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "title", nullable = false, length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "symbol_left", nullable = false, length = 12)
	public String getSymbolLeft() {
		return this.symbolLeft;
	}

	public void setSymbolLeft(String symbolLeft) {
		this.symbolLeft = symbolLeft;
	}

	@Column(name = "symbol_right", nullable = false, length = 12)
	public String getSymbolRight() {
		return this.symbolRight;
	}

	public void setSymbolRight(String symbolRight) {
		this.symbolRight = symbolRight;
	}

	@Column(name = "decimal_place", nullable = false, length = 1)
	public char getDecimalPlace() {
		return this.decimalPlace;
	}

	public void setDecimalPlace(char decimalPlace) {
		this.decimalPlace = decimalPlace;
	}

	@Column(name = "value", nullable = false, precision = 15, scale = 8)
	public float getValue() {
		return this.value;
	}

	public void setValue(float value) {
		this.value = value;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
