package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcCustomerFieldId generated by hbm2java
 */
@Embeddable
public class CustomerFieldId implements java.io.Serializable {

	private int customerId;
	private int customFieldId;
	private int customFieldValueId;

	public CustomerFieldId() {
	}

	public CustomerFieldId(int customerId, int customFieldId,
			int customFieldValueId) {
		this.customerId = customerId;
		this.customFieldId = customFieldId;
		this.customFieldValueId = customFieldValueId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "custom_field_id", nullable = false)
	public int getCustomFieldId() {
		return this.customFieldId;
	}

	public void setCustomFieldId(int customFieldId) {
		this.customFieldId = customFieldId;
	}

	@Column(name = "custom_field_value_id", nullable = false)
	public int getCustomFieldValueId() {
		return this.customFieldValueId;
	}

	public void setCustomFieldValueId(int customFieldValueId) {
		this.customFieldValueId = customFieldValueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerFieldId))
			return false;
		CustomerFieldId castOther = (CustomerFieldId) other;

		return (this.getCustomerId() == castOther.getCustomerId())
				&& (this.getCustomFieldId() == castOther.getCustomFieldId())
				&& (this.getCustomFieldValueId() == castOther
						.getCustomFieldValueId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerId();
		result = 37 * result + this.getCustomFieldId();
		result = 37 * result + this.getCustomFieldValueId();
		return result;
	}

}
