package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCustomer generated by hbm2java
 */
@Entity
@Table(name = "oc_customer", catalog = "opencart")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private int storeId;
	private String firstname;
	private String lastname;
	private String email;
	private String telephone;
	private String fax;
	private String password;
	private String salt;
	private String cart;
	private String wishlist;
	private boolean newsletter;
	private int addressId;
	private int customerGroupId;
	private String ip;
	private boolean status;
	private boolean approved;
	private String token;
	private Date dateAdded;

	public Customer() {
	}

	public Customer(int storeId, String firstname, String lastname,
			String email, String telephone, String fax, String password,
			String salt, boolean newsletter, int addressId,
			int customerGroupId, String ip, boolean status, boolean approved,
			String token, Date dateAdded) {
		this.storeId = storeId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.password = password;
		this.salt = salt;
		this.newsletter = newsletter;
		this.addressId = addressId;
		this.customerGroupId = customerGroupId;
		this.ip = ip;
		this.status = status;
		this.approved = approved;
		this.token = token;
		this.dateAdded = dateAdded;
	}

	public Customer(int storeId, String firstname, String lastname,
			String email, String telephone, String fax, String password,
			String salt, String cart, String wishlist, boolean newsletter,
			int addressId, int customerGroupId, String ip, boolean status,
			boolean approved, String token, Date dateAdded) {
		this.storeId = storeId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.password = password;
		this.salt = salt;
		this.cart = cart;
		this.wishlist = wishlist;
		this.newsletter = newsletter;
		this.addressId = addressId;
		this.customerGroupId = customerGroupId;
		this.ip = ip;
		this.status = status;
		this.approved = approved;
		this.token = token;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@Column(name = "firstname", nullable = false, length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 96)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", nullable = false, length = 32)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 32)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "password", nullable = false, length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false, length = 9)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "cart", length = 65535)
	public String getCart() {
		return this.cart;
	}

	public void setCart(String cart) {
		this.cart = cart;
	}

	@Column(name = "wishlist", length = 65535)
	public String getWishlist() {
		return this.wishlist;
	}

	public void setWishlist(String wishlist) {
		this.wishlist = wishlist;
	}

	@Column(name = "newsletter", nullable = false)
	public boolean isNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		this.newsletter = newsletter;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "customer_group_id", nullable = false)
	public int getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(int customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "ip", nullable = false, length = 40)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	@Column(name = "token", nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
