package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCustomerOnline generated by hbm2java
 */
@Entity
@Table(name = "oc_customer_online", catalog = "opencart")
public class CustomerOnline implements java.io.Serializable {

	private String ip;
	private int customerId;
	private String url;
	private String referer;
	private Date dateAdded;

	public CustomerOnline() {
	}

	public CustomerOnline(String ip, int customerId, String url,
			String referer, Date dateAdded) {
		this.ip = ip;
		this.customerId = customerId;
		this.url = url;
		this.referer = referer;
		this.dateAdded = dateAdded;
	}

	@Id
	@Column(name = "ip", unique = true, nullable = false, length = 40)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "url", nullable = false, length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "referer", nullable = false, length = 65535)
	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
