package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCustomerHistory generated by hbm2java
 */
@Entity
@Table(name = "oc_customer_history", catalog = "opencart")
public class CustomerHistory implements java.io.Serializable {

	private Integer customerHistoryId;
	private int customerId;
	private String comment;
	private Date dateAdded;

	public CustomerHistory() {
	}

	public CustomerHistory(int customerId, String comment, Date dateAdded) {
		this.customerId = customerId;
		this.comment = comment;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_history_id", unique = true, nullable = false)
	public Integer getCustomerHistoryId() {
		return this.customerHistoryId;
	}

	public void setCustomerHistoryId(Integer customerHistoryId) {
		this.customerHistoryId = customerHistoryId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "comment", nullable = false, length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
