package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCustomFieldValueDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_custom_field_value_description", catalog = "opencart")
public class CustomFieldValueDescription implements java.io.Serializable {

	private CustomFieldValueDescriptionId id;
	private int customFieldId;
	private String name;

	public CustomFieldValueDescription() {
	}

	public CustomFieldValueDescription(CustomFieldValueDescriptionId id,
			int customFieldId, String name) {
		this.id = id;
		this.customFieldId = customFieldId;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customFieldValueId", column = @Column(name = "custom_field_value_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public CustomFieldValueDescriptionId getId() {
		return this.id;
	}

	public void setId(CustomFieldValueDescriptionId id) {
		this.id = id;
	}

	@Column(name = "custom_field_id", nullable = false)
	public int getCustomFieldId() {
		return this.customFieldId;
	}

	public void setCustomFieldId(int customFieldId) {
		this.customFieldId = customFieldId;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
