package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcCustomFieldToCustomerGroupId generated by hbm2java
 */
@Embeddable
public class CustomFieldToCustomerGroupId implements java.io.Serializable {

	private int customFieldId;
	private int customerGroupId;

	public CustomFieldToCustomerGroupId() {
	}

	public CustomFieldToCustomerGroupId(int customFieldId, int customerGroupId) {
		this.customFieldId = customFieldId;
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "custom_field_id", nullable = false)
	public int getCustomFieldId() {
		return this.customFieldId;
	}

	public void setCustomFieldId(int customFieldId) {
		this.customFieldId = customFieldId;
	}

	@Column(name = "customer_group_id", nullable = false)
	public int getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(int customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomFieldToCustomerGroupId))
			return false;
		CustomFieldToCustomerGroupId castOther = (CustomFieldToCustomerGroupId) other;

		return (this.getCustomFieldId() == castOther.getCustomFieldId())
				&& (this.getCustomerGroupId() == castOther.getCustomerGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomFieldId();
		result = 37 * result + this.getCustomerGroupId();
		return result;
	}

}
