package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCustomFieldToCustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "oc_custom_field_to_customer_group", catalog = "opencart")
public class CustomFieldToCustomerGroup implements java.io.Serializable {

	private CustomFieldToCustomerGroupId id;

	public CustomFieldToCustomerGroup() {
	}

	public CustomFieldToCustomerGroup(CustomFieldToCustomerGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customFieldId", column = @Column(name = "custom_field_id", nullable = false)),
			@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)) })
	public CustomFieldToCustomerGroupId getId() {
		return this.id;
	}

	public void setId(CustomFieldToCustomerGroupId id) {
		this.id = id;
	}

}
