package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcCustomFieldDescriptionId generated by hbm2java
 */
@Embeddable
public class CustomFieldDescriptionId implements java.io.Serializable {

	private int customFieldId;
	private int languageId;

	public CustomFieldDescriptionId() {
	}

	public CustomFieldDescriptionId(int customFieldId, int languageId) {
		this.customFieldId = customFieldId;
		this.languageId = languageId;
	}

	@Column(name = "custom_field_id", nullable = false)
	public int getCustomFieldId() {
		return this.customFieldId;
	}

	public void setCustomFieldId(int customFieldId) {
		this.customFieldId = customFieldId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomFieldDescriptionId))
			return false;
		CustomFieldDescriptionId castOther = (CustomFieldDescriptionId) other;

		return (this.getCustomFieldId() == castOther.getCustomFieldId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomFieldId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
