package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcCustomerGroupDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_customer_group_description", catalog = "opencart")
public class CustomerGroupDescription implements java.io.Serializable {

	private CustomerGroupDescriptionId id;
	private String name;
	private String description;

	public CustomerGroupDescription() {
	}

	public CustomerGroupDescription(CustomerGroupDescriptionId id,
			String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public CustomerGroupDescriptionId getId() {
		return this.id;
	}

	public void setId(CustomerGroupDescriptionId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
