package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCustomerReward generated by hbm2java
 */
@Entity
@Table(name = "oc_customer_reward", catalog = "opencart")
public class CustomerReward implements java.io.Serializable {

	private Integer customerRewardId;
	private int customerId;
	private int orderId;
	private String description;
	private int points;
	private Date dateAdded;

	public CustomerReward() {
	}

	public CustomerReward(int customerId, int orderId, String description,
			int points, Date dateAdded) {
		this.customerId = customerId;
		this.orderId = orderId;
		this.description = description;
		this.points = points;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_reward_id", unique = true, nullable = false)
	public Integer getCustomerRewardId() {
		return this.customerRewardId;
	}

	public void setCustomerRewardId(Integer customerRewardId) {
		this.customerRewardId = customerRewardId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
