package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcCustomerIp generated by hbm2java
 */
@Entity
@Table(name = "oc_customer_ip", catalog = "opencart")
public class CustomerIp implements java.io.Serializable {

	private Integer customerIpId;
	private int customerId;
	private String ip;
	private Date dateAdded;

	public CustomerIp() {
	}

	public CustomerIp(int customerId, String ip, Date dateAdded) {
		this.customerId = customerId;
		this.ip = ip;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_ip_id", unique = true, nullable = false)
	public Integer getCustomerIpId() {
		return this.customerIpId;
	}

	public void setCustomerIpId(Integer customerIpId) {
		this.customerIpId = customerIpId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "ip", nullable = false, length = 40)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
