package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcDownloadDescriptionId generated by hbm2java
 */
@Embeddable
public class DownloadDescriptionId implements java.io.Serializable {

	private int downloadId;
	private int languageId;

	public DownloadDescriptionId() {
	}

	public DownloadDescriptionId(int downloadId, int languageId) {
		this.downloadId = downloadId;
		this.languageId = languageId;
	}

	@Column(name = "download_id", nullable = false)
	public int getDownloadId() {
		return this.downloadId;
	}

	public void setDownloadId(int downloadId) {
		this.downloadId = downloadId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DownloadDescriptionId))
			return false;
		DownloadDescriptionId castOther = (DownloadDescriptionId) other;

		return (this.getDownloadId() == castOther.getDownloadId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDownloadId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
