package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcFilter generated by hbm2java
 */
@Entity
@Table(name = "oc_filter", catalog = "opencart")
public class Filter implements java.io.Serializable {

	private Integer filterId;
	private int filterGroupId;
	private int sortOrder;

	public Filter() {
	}

	public Filter(int filterGroupId, int sortOrder) {
		this.filterGroupId = filterGroupId;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "filter_id", unique = true, nullable = false)
	public Integer getFilterId() {
		return this.filterId;
	}

	public void setFilterId(Integer filterId) {
		this.filterId = filterId;
	}

	@Column(name = "filter_group_id", nullable = false)
	public int getFilterGroupId() {
		return this.filterGroupId;
	}

	public void setFilterGroupId(int filterGroupId) {
		this.filterGroupId = filterGroupId;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
