package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcFilterGroupDescriptionId generated by hbm2java
 */
@Embeddable
public class FilterGroupDescriptionId implements java.io.Serializable {

	private int filterGroupId;
	private int languageId;

	public FilterGroupDescriptionId() {
	}

	public FilterGroupDescriptionId(int filterGroupId, int languageId) {
		this.filterGroupId = filterGroupId;
		this.languageId = languageId;
	}

	@Column(name = "filter_group_id", nullable = false)
	public int getFilterGroupId() {
		return this.filterGroupId;
	}

	public void setFilterGroupId(int filterGroupId) {
		this.filterGroupId = filterGroupId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FilterGroupDescriptionId))
			return false;
		FilterGroupDescriptionId castOther = (FilterGroupDescriptionId) other;

		return (this.getFilterGroupId() == castOther.getFilterGroupId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFilterGroupId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
