package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcFilterGroup generated by hbm2java
 */
@Entity
@Table(name = "oc_filter_group", catalog = "opencart")
public class FilterGroup implements java.io.Serializable {

	private Integer filterGroupId;
	private int sortOrder;

	public FilterGroup() {
	}

	public FilterGroup(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "filter_group_id", unique = true, nullable = false)
	public Integer getFilterGroupId() {
		return this.filterGroupId;
	}

	public void setFilterGroupId(Integer filterGroupId) {
		this.filterGroupId = filterGroupId;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
