package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcInformationToStore generated by hbm2java
 */
@Entity
@Table(name = "oc_information_to_store", catalog = "opencart")
public class InformationToStore implements java.io.Serializable {

	private InformationToStoreId id;

	public InformationToStore() {
	}

	public InformationToStore(InformationToStoreId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "informationId", column = @Column(name = "information_id", nullable = false)),
			@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)) })
	public InformationToStoreId getId() {
		return this.id;
	}

	public void setId(InformationToStoreId id) {
		this.id = id;
	}

}
