package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcLayoutRoute generated by hbm2java
 */
@Entity
@Table(name = "oc_layout_route", catalog = "opencart")
public class LayoutRoute implements java.io.Serializable {

	private Integer layoutRouteId;
	private int layoutId;
	private int storeId;
	private String route;

	public LayoutRoute() {
	}

	public LayoutRoute(int layoutId, int storeId, String route) {
		this.layoutId = layoutId;
		this.storeId = storeId;
		this.route = route;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "layout_route_id", unique = true, nullable = false)
	public Integer getLayoutRouteId() {
		return this.layoutRouteId;
	}

	public void setLayoutRouteId(Integer layoutRouteId) {
		this.layoutRouteId = layoutRouteId;
	}

	@Column(name = "layout_id", nullable = false)
	public int getLayoutId() {
		return this.layoutId;
	}

	public void setLayoutId(int layoutId) {
		this.layoutId = layoutId;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@Column(name = "route", nullable = false)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

}
