package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcManufacturer generated by hbm2java
 */
@Entity
@Table(name = "oc_manufacturer", catalog = "opencart")
public class Manufacturer implements java.io.Serializable {

	private Integer manufacturerId;
	private String name;
	private String image;
	private int sortOrder;

	public Manufacturer() {
	}

	public Manufacturer(String name, int sortOrder) {
		this.name = name;
		this.sortOrder = sortOrder;
	}

	public Manufacturer(String name, String image, int sortOrder) {
		this.name = name;
		this.image = image;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "manufacturer_id", unique = true, nullable = false)
	public Integer getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(Integer manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
