package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcManufacturerToStoreId generated by hbm2java
 */
@Embeddable
public class ManufacturerToStoreId implements java.io.Serializable {

	private int manufacturerId;
	private int storeId;

	public ManufacturerToStoreId() {
	}

	public ManufacturerToStoreId(int manufacturerId, int storeId) {
		this.manufacturerId = manufacturerId;
		this.storeId = storeId;
	}

	@Column(name = "manufacturer_id", nullable = false)
	public int getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(int manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ManufacturerToStoreId))
			return false;
		ManufacturerToStoreId castOther = (ManufacturerToStoreId) other;

		return (this.getManufacturerId() == castOther.getManufacturerId())
				&& (this.getStoreId() == castOther.getStoreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getManufacturerId();
		result = 37 * result + this.getStoreId();
		return result;
	}

}
