package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcOptionValueDescriptionId generated by hbm2java
 */
@Embeddable
public class OptionValueDescriptionId implements java.io.Serializable {

	private int optionValueId;
	private int languageId;

	public OptionValueDescriptionId() {
	}

	public OptionValueDescriptionId(int optionValueId, int languageId) {
		this.optionValueId = optionValueId;
		this.languageId = languageId;
	}

	@Column(name = "option_value_id", nullable = false)
	public int getOptionValueId() {
		return this.optionValueId;
	}

	public void setOptionValueId(int optionValueId) {
		this.optionValueId = optionValueId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OptionValueDescriptionId))
			return false;
		OptionValueDescriptionId castOther = (OptionValueDescriptionId) other;

		return (this.getOptionValueId() == castOther.getOptionValueId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOptionValueId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
