package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcOptionValue generated by hbm2java
 */
@Entity
@Table(name = "oc_option_value", catalog = "opencart")
public class OptionValue implements java.io.Serializable {

	private Integer optionValueId;
	private int optionId;
	private String image;
	private int sortOrder;

	public OptionValue() {
	}

	public OptionValue(int optionId, String image, int sortOrder) {
		this.optionId = optionId;
		this.image = image;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "option_value_id", unique = true, nullable = false)
	public Integer getOptionValueId() {
		return this.optionValueId;
	}

	public void setOptionValueId(Integer optionValueId) {
		this.optionValueId = optionValueId;
	}

	@Column(name = "option_id", nullable = false)
	public int getOptionId() {
		return this.optionId;
	}

	public void setOptionId(int optionId) {
		this.optionId = optionId;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
