package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcOptionDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_option_description", catalog = "opencart")
public class OptionDescription implements java.io.Serializable {

	private OptionDescriptionId id;
	private String name;

	public OptionDescription() {
	}

	public OptionDescription(OptionDescriptionId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "optionId", column = @Column(name = "option_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public OptionDescriptionId getId() {
		return this.id;
	}

	public void setId(OptionDescriptionId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
