package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcOrderProduct generated by hbm2java
 */
@Entity
@Table(name = "oc_order_product", catalog = "opencart")
public class OrderProduct implements java.io.Serializable {

	private Integer orderProductId;
	private int orderId;
	private int productId;
	private String name;
	private String model;
	private int quantity;
	private BigDecimal price;
	private BigDecimal total;
	private BigDecimal tax;
	private int reward;

	public OrderProduct() {
	}

	public OrderProduct(int orderId, int productId, String name,
			String model, int quantity, BigDecimal price, BigDecimal total,
			BigDecimal tax, int reward) {
		this.orderId = orderId;
		this.productId = productId;
		this.name = name;
		this.model = model;
		this.quantity = quantity;
		this.price = price;
		this.total = total;
		this.tax = tax;
		this.reward = reward;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_product_id", unique = true, nullable = false)
	public Integer getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(Integer orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "model", nullable = false, length = 64)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 15, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "total", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "tax", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "reward", nullable = false)
	public int getReward() {
		return this.reward;
	}

	public void setReward(int reward) {
		this.reward = reward;
	}

}
