package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcOrderHistory generated by hbm2java
 */
@Entity
@Table(name = "oc_order_history", catalog = "opencart")
public class OrderHistory implements java.io.Serializable {

	private Integer orderHistoryId;
	private int orderId;
	private int orderStatusId;
	private boolean notify;
	private String comment;
	private Date dateAdded;

	public OrderHistory() {
	}

	public OrderHistory(int orderId, int orderStatusId, boolean notify,
			String comment, Date dateAdded) {
		this.orderId = orderId;
		this.orderStatusId = orderStatusId;
		this.notify = notify;
		this.comment = comment;
		this.dateAdded = dateAdded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_history_id", unique = true, nullable = false)
	public Integer getOrderHistoryId() {
		return this.orderHistoryId;
	}

	public void setOrderHistoryId(Integer orderHistoryId) {
		this.orderHistoryId = orderHistoryId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_status_id", nullable = false)
	public int getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(int orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "notify", nullable = false)
	public boolean isNotify() {
		return this.notify;
	}

	public void setNotify(boolean notify) {
		this.notify = notify;
	}

	@Column(name = "comment", nullable = false, length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
