package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcOrderTotal generated by hbm2java
 */
@Entity
@Table(name = "oc_order_total", catalog = "opencart")
public class OrderTotal implements java.io.Serializable {

	private Integer orderTotalId;
	private int orderId;
	private String code;
	private String title;
	private String text;
	private BigDecimal value;
	private int sortOrder;

	public OrderTotal() {
	}

	public OrderTotal(int orderId, String code, String title, String text,
			BigDecimal value, int sortOrder) {
		this.orderId = orderId;
		this.code = code;
		this.title = title;
		this.text = text;
		this.value = value;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_total_id", unique = true, nullable = false)
	public Integer getOrderTotalId() {
		return this.orderTotalId;
	}

	public void setOrderTotalId(Integer orderTotalId) {
		this.orderTotalId = orderTotalId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "code", nullable = false, length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "value", nullable = false, precision = 15, scale = 4)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
