package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcOrderFraud generated by hbm2java
 */
@Entity
@Table(name = "oc_order_fraud", catalog = "opencart")
public class OrderFraud implements java.io.Serializable {

	private int orderId;
	private int customerId;
	private String countryMatch;
	private String countryCode;
	private String highRiskCountry;
	private int distance;
	private String ipRegion;
	private String ipCity;
	private BigDecimal ipLatitude;
	private BigDecimal ipLongitude;
	private String ipIsp;
	private String ipOrg;
	private int ipAsnum;
	private String ipUserType;
	private String ipCountryConfidence;
	private String ipRegionConfidence;
	private String ipCityConfidence;
	private String ipPostalConfidence;
	private String ipPostalCode;
	private int ipAccuracyRadius;
	private String ipNetSpeedCell;
	private int ipMetroCode;
	private int ipAreaCode;
	private String ipTimeZone;
	private String ipRegionName;
	private String ipDomain;
	private String ipCountryName;
	private String ipContinentCode;
	private String ipCorporateProxy;
	private String anonymousProxy;
	private int proxyScore;
	private String isTransProxy;
	private String freeMail;
	private String carderEmail;
	private String highRiskUsername;
	private String highRiskPassword;
	private String binMatch;
	private String binCountry;
	private String binNameMatch;
	private String binName;
	private String binPhoneMatch;
	private String binPhone;
	private String customerPhoneInBillingLocation;
	private String shipForward;
	private String cityPostalMatch;
	private String shipCityPostalMatch;
	private BigDecimal score;
	private String explanation;
	private BigDecimal riskScore;
	private int queriesRemaining;
	private String maxmindId;
	private String error;
	private Date dateAdded;

	public OrderFraud() {
	}

	public OrderFraud(int orderId, int customerId, String countryMatch,
			String countryCode, String highRiskCountry, int distance,
			String ipRegion, String ipCity, BigDecimal ipLatitude,
			BigDecimal ipLongitude, String ipIsp, String ipOrg, int ipAsnum,
			String ipUserType, String ipCountryConfidence,
			String ipRegionConfidence, String ipCityConfidence,
			String ipPostalConfidence, String ipPostalCode,
			int ipAccuracyRadius, String ipNetSpeedCell, int ipMetroCode,
			int ipAreaCode, String ipTimeZone, String ipRegionName,
			String ipDomain, String ipCountryName, String ipContinentCode,
			String ipCorporateProxy, String anonymousProxy, int proxyScore,
			String isTransProxy, String freeMail, String carderEmail,
			String highRiskUsername, String highRiskPassword, String binMatch,
			String binCountry, String binNameMatch, String binName,
			String binPhoneMatch, String binPhone,
			String customerPhoneInBillingLocation, String shipForward,
			String cityPostalMatch, String shipCityPostalMatch,
			BigDecimal score, String explanation, BigDecimal riskScore,
			int queriesRemaining, String maxmindId, String error, Date dateAdded) {
		this.orderId = orderId;
		this.customerId = customerId;
		this.countryMatch = countryMatch;
		this.countryCode = countryCode;
		this.highRiskCountry = highRiskCountry;
		this.distance = distance;
		this.ipRegion = ipRegion;
		this.ipCity = ipCity;
		this.ipLatitude = ipLatitude;
		this.ipLongitude = ipLongitude;
		this.ipIsp = ipIsp;
		this.ipOrg = ipOrg;
		this.ipAsnum = ipAsnum;
		this.ipUserType = ipUserType;
		this.ipCountryConfidence = ipCountryConfidence;
		this.ipRegionConfidence = ipRegionConfidence;
		this.ipCityConfidence = ipCityConfidence;
		this.ipPostalConfidence = ipPostalConfidence;
		this.ipPostalCode = ipPostalCode;
		this.ipAccuracyRadius = ipAccuracyRadius;
		this.ipNetSpeedCell = ipNetSpeedCell;
		this.ipMetroCode = ipMetroCode;
		this.ipAreaCode = ipAreaCode;
		this.ipTimeZone = ipTimeZone;
		this.ipRegionName = ipRegionName;
		this.ipDomain = ipDomain;
		this.ipCountryName = ipCountryName;
		this.ipContinentCode = ipContinentCode;
		this.ipCorporateProxy = ipCorporateProxy;
		this.anonymousProxy = anonymousProxy;
		this.proxyScore = proxyScore;
		this.isTransProxy = isTransProxy;
		this.freeMail = freeMail;
		this.carderEmail = carderEmail;
		this.highRiskUsername = highRiskUsername;
		this.highRiskPassword = highRiskPassword;
		this.binMatch = binMatch;
		this.binCountry = binCountry;
		this.binNameMatch = binNameMatch;
		this.binName = binName;
		this.binPhoneMatch = binPhoneMatch;
		this.binPhone = binPhone;
		this.customerPhoneInBillingLocation = customerPhoneInBillingLocation;
		this.shipForward = shipForward;
		this.cityPostalMatch = cityPostalMatch;
		this.shipCityPostalMatch = shipCityPostalMatch;
		this.score = score;
		this.explanation = explanation;
		this.riskScore = riskScore;
		this.queriesRemaining = queriesRemaining;
		this.maxmindId = maxmindId;
		this.error = error;
		this.dateAdded = dateAdded;
	}

	@Id
	@Column(name = "order_id", unique = true, nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "country_match", nullable = false, length = 3)
	public String getCountryMatch() {
		return this.countryMatch;
	}

	public void setCountryMatch(String countryMatch) {
		this.countryMatch = countryMatch;
	}

	@Column(name = "country_code", nullable = false, length = 2)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "high_risk_country", nullable = false, length = 3)
	public String getHighRiskCountry() {
		return this.highRiskCountry;
	}

	public void setHighRiskCountry(String highRiskCountry) {
		this.highRiskCountry = highRiskCountry;
	}

	@Column(name = "distance", nullable = false)
	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

	@Column(name = "ip_region", nullable = false)
	public String getIpRegion() {
		return this.ipRegion;
	}

	public void setIpRegion(String ipRegion) {
		this.ipRegion = ipRegion;
	}

	@Column(name = "ip_city", nullable = false)
	public String getIpCity() {
		return this.ipCity;
	}

	public void setIpCity(String ipCity) {
		this.ipCity = ipCity;
	}

	@Column(name = "ip_latitude", nullable = false, precision = 10, scale = 6)
	public BigDecimal getIpLatitude() {
		return this.ipLatitude;
	}

	public void setIpLatitude(BigDecimal ipLatitude) {
		this.ipLatitude = ipLatitude;
	}

	@Column(name = "ip_longitude", nullable = false, precision = 10, scale = 6)
	public BigDecimal getIpLongitude() {
		return this.ipLongitude;
	}

	public void setIpLongitude(BigDecimal ipLongitude) {
		this.ipLongitude = ipLongitude;
	}

	@Column(name = "ip_isp", nullable = false)
	public String getIpIsp() {
		return this.ipIsp;
	}

	public void setIpIsp(String ipIsp) {
		this.ipIsp = ipIsp;
	}

	@Column(name = "ip_org", nullable = false)
	public String getIpOrg() {
		return this.ipOrg;
	}

	public void setIpOrg(String ipOrg) {
		this.ipOrg = ipOrg;
	}

	@Column(name = "ip_asnum", nullable = false)
	public int getIpAsnum() {
		return this.ipAsnum;
	}

	public void setIpAsnum(int ipAsnum) {
		this.ipAsnum = ipAsnum;
	}

	@Column(name = "ip_user_type", nullable = false)
	public String getIpUserType() {
		return this.ipUserType;
	}

	public void setIpUserType(String ipUserType) {
		this.ipUserType = ipUserType;
	}

	@Column(name = "ip_country_confidence", nullable = false, length = 3)
	public String getIpCountryConfidence() {
		return this.ipCountryConfidence;
	}

	public void setIpCountryConfidence(String ipCountryConfidence) {
		this.ipCountryConfidence = ipCountryConfidence;
	}

	@Column(name = "ip_region_confidence", nullable = false, length = 3)
	public String getIpRegionConfidence() {
		return this.ipRegionConfidence;
	}

	public void setIpRegionConfidence(String ipRegionConfidence) {
		this.ipRegionConfidence = ipRegionConfidence;
	}

	@Column(name = "ip_city_confidence", nullable = false, length = 3)
	public String getIpCityConfidence() {
		return this.ipCityConfidence;
	}

	public void setIpCityConfidence(String ipCityConfidence) {
		this.ipCityConfidence = ipCityConfidence;
	}

	@Column(name = "ip_postal_confidence", nullable = false, length = 3)
	public String getIpPostalConfidence() {
		return this.ipPostalConfidence;
	}

	public void setIpPostalConfidence(String ipPostalConfidence) {
		this.ipPostalConfidence = ipPostalConfidence;
	}

	@Column(name = "ip_postal_code", nullable = false, length = 10)
	public String getIpPostalCode() {
		return this.ipPostalCode;
	}

	public void setIpPostalCode(String ipPostalCode) {
		this.ipPostalCode = ipPostalCode;
	}

	@Column(name = "ip_accuracy_radius", nullable = false)
	public int getIpAccuracyRadius() {
		return this.ipAccuracyRadius;
	}

	public void setIpAccuracyRadius(int ipAccuracyRadius) {
		this.ipAccuracyRadius = ipAccuracyRadius;
	}

	@Column(name = "ip_net_speed_cell", nullable = false)
	public String getIpNetSpeedCell() {
		return this.ipNetSpeedCell;
	}

	public void setIpNetSpeedCell(String ipNetSpeedCell) {
		this.ipNetSpeedCell = ipNetSpeedCell;
	}

	@Column(name = "ip_metro_code", nullable = false)
	public int getIpMetroCode() {
		return this.ipMetroCode;
	}

	public void setIpMetroCode(int ipMetroCode) {
		this.ipMetroCode = ipMetroCode;
	}

	@Column(name = "ip_area_code", nullable = false)
	public int getIpAreaCode() {
		return this.ipAreaCode;
	}

	public void setIpAreaCode(int ipAreaCode) {
		this.ipAreaCode = ipAreaCode;
	}

	@Column(name = "ip_time_zone", nullable = false)
	public String getIpTimeZone() {
		return this.ipTimeZone;
	}

	public void setIpTimeZone(String ipTimeZone) {
		this.ipTimeZone = ipTimeZone;
	}

	@Column(name = "ip_region_name", nullable = false)
	public String getIpRegionName() {
		return this.ipRegionName;
	}

	public void setIpRegionName(String ipRegionName) {
		this.ipRegionName = ipRegionName;
	}

	@Column(name = "ip_domain", nullable = false)
	public String getIpDomain() {
		return this.ipDomain;
	}

	public void setIpDomain(String ipDomain) {
		this.ipDomain = ipDomain;
	}

	@Column(name = "ip_country_name", nullable = false)
	public String getIpCountryName() {
		return this.ipCountryName;
	}

	public void setIpCountryName(String ipCountryName) {
		this.ipCountryName = ipCountryName;
	}

	@Column(name = "ip_continent_code", nullable = false, length = 2)
	public String getIpContinentCode() {
		return this.ipContinentCode;
	}

	public void setIpContinentCode(String ipContinentCode) {
		this.ipContinentCode = ipContinentCode;
	}

	@Column(name = "ip_corporate_proxy", nullable = false, length = 3)
	public String getIpCorporateProxy() {
		return this.ipCorporateProxy;
	}

	public void setIpCorporateProxy(String ipCorporateProxy) {
		this.ipCorporateProxy = ipCorporateProxy;
	}

	@Column(name = "anonymous_proxy", nullable = false, length = 3)
	public String getAnonymousProxy() {
		return this.anonymousProxy;
	}

	public void setAnonymousProxy(String anonymousProxy) {
		this.anonymousProxy = anonymousProxy;
	}

	@Column(name = "proxy_score", nullable = false)
	public int getProxyScore() {
		return this.proxyScore;
	}

	public void setProxyScore(int proxyScore) {
		this.proxyScore = proxyScore;
	}

	@Column(name = "is_trans_proxy", nullable = false, length = 3)
	public String getIsTransProxy() {
		return this.isTransProxy;
	}

	public void setIsTransProxy(String isTransProxy) {
		this.isTransProxy = isTransProxy;
	}

	@Column(name = "free_mail", nullable = false, length = 3)
	public String getFreeMail() {
		return this.freeMail;
	}

	public void setFreeMail(String freeMail) {
		this.freeMail = freeMail;
	}

	@Column(name = "carder_email", nullable = false, length = 3)
	public String getCarderEmail() {
		return this.carderEmail;
	}

	public void setCarderEmail(String carderEmail) {
		this.carderEmail = carderEmail;
	}

	@Column(name = "high_risk_username", nullable = false, length = 3)
	public String getHighRiskUsername() {
		return this.highRiskUsername;
	}

	public void setHighRiskUsername(String highRiskUsername) {
		this.highRiskUsername = highRiskUsername;
	}

	@Column(name = "high_risk_password", nullable = false, length = 3)
	public String getHighRiskPassword() {
		return this.highRiskPassword;
	}

	public void setHighRiskPassword(String highRiskPassword) {
		this.highRiskPassword = highRiskPassword;
	}

	@Column(name = "bin_match", nullable = false, length = 10)
	public String getBinMatch() {
		return this.binMatch;
	}

	public void setBinMatch(String binMatch) {
		this.binMatch = binMatch;
	}

	@Column(name = "bin_country", nullable = false, length = 2)
	public String getBinCountry() {
		return this.binCountry;
	}

	public void setBinCountry(String binCountry) {
		this.binCountry = binCountry;
	}

	@Column(name = "bin_name_match", nullable = false, length = 3)
	public String getBinNameMatch() {
		return this.binNameMatch;
	}

	public void setBinNameMatch(String binNameMatch) {
		this.binNameMatch = binNameMatch;
	}

	@Column(name = "bin_name", nullable = false)
	public String getBinName() {
		return this.binName;
	}

	public void setBinName(String binName) {
		this.binName = binName;
	}

	@Column(name = "bin_phone_match", nullable = false, length = 3)
	public String getBinPhoneMatch() {
		return this.binPhoneMatch;
	}

	public void setBinPhoneMatch(String binPhoneMatch) {
		this.binPhoneMatch = binPhoneMatch;
	}

	@Column(name = "bin_phone", nullable = false, length = 32)
	public String getBinPhone() {
		return this.binPhone;
	}

	public void setBinPhone(String binPhone) {
		this.binPhone = binPhone;
	}

	@Column(name = "customer_phone_in_billing_location", nullable = false, length = 8)
	public String getCustomerPhoneInBillingLocation() {
		return this.customerPhoneInBillingLocation;
	}

	public void setCustomerPhoneInBillingLocation(
			String customerPhoneInBillingLocation) {
		this.customerPhoneInBillingLocation = customerPhoneInBillingLocation;
	}

	@Column(name = "ship_forward", nullable = false, length = 3)
	public String getShipForward() {
		return this.shipForward;
	}

	public void setShipForward(String shipForward) {
		this.shipForward = shipForward;
	}

	@Column(name = "city_postal_match", nullable = false, length = 3)
	public String getCityPostalMatch() {
		return this.cityPostalMatch;
	}

	public void setCityPostalMatch(String cityPostalMatch) {
		this.cityPostalMatch = cityPostalMatch;
	}

	@Column(name = "ship_city_postal_match", nullable = false, length = 3)
	public String getShipCityPostalMatch() {
		return this.shipCityPostalMatch;
	}

	public void setShipCityPostalMatch(String shipCityPostalMatch) {
		this.shipCityPostalMatch = shipCityPostalMatch;
	}

	@Column(name = "score", nullable = false, precision = 10, scale = 5)
	public BigDecimal getScore() {
		return this.score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}

	@Column(name = "explanation", nullable = false, length = 65535)
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	@Column(name = "risk_score", nullable = false, precision = 10, scale = 5)
	public BigDecimal getRiskScore() {
		return this.riskScore;
	}

	public void setRiskScore(BigDecimal riskScore) {
		this.riskScore = riskScore;
	}

	@Column(name = "queries_remaining", nullable = false)
	public int getQueriesRemaining() {
		return this.queriesRemaining;
	}

	public void setQueriesRemaining(int queriesRemaining) {
		this.queriesRemaining = queriesRemaining;
	}

	@Column(name = "maxmind_id", nullable = false, length = 8)
	public String getMaxmindId() {
		return this.maxmindId;
	}

	public void setMaxmindId(String maxmindId) {
		this.maxmindId = maxmindId;
	}

	@Column(name = "error", nullable = false, length = 65535)
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
