package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcOrderOption generated by hbm2java
 */
@Entity
@Table(name = "oc_order_option", catalog = "opencart")
public class OrderOption implements java.io.Serializable {

	private Integer orderOptionId;
	private int orderId;
	private int orderProductId;
	private int productOptionId;
	private int productOptionValueId;
	private String name;
	private String value;
	private String type;

	public OrderOption() {
	}

	public OrderOption(int orderId, int orderProductId, int productOptionId,
			int productOptionValueId, String name, String value, String type) {
		this.orderId = orderId;
		this.orderProductId = orderProductId;
		this.productOptionId = productOptionId;
		this.productOptionValueId = productOptionValueId;
		this.name = name;
		this.value = value;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_option_id", unique = true, nullable = false)
	public Integer getOrderOptionId() {
		return this.orderOptionId;
	}

	public void setOrderOptionId(Integer orderOptionId) {
		this.orderOptionId = orderOptionId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_product_id", nullable = false)
	public int getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(int orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "product_option_id", nullable = false)
	public int getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(int productOptionId) {
		this.productOptionId = productOptionId;
	}

	@Column(name = "product_option_value_id", nullable = false)
	public int getProductOptionValueId() {
		return this.productOptionValueId;
	}

	public void setProductOptionValueId(int productOptionValueId) {
		this.productOptionValueId = productOptionValueId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
