package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcOrderDownload generated by hbm2java
 */
@Entity
@Table(name = "oc_order_download", catalog = "opencart")
public class OrderDownload implements java.io.Serializable {

	private Integer orderDownloadId;
	private int orderId;
	private int orderProductId;
	private String name;
	private String filename;
	private String mask;
	private int remaining;

	public OrderDownload() {
	}

	public OrderDownload(int orderId, int orderProductId, String name,
			String filename, String mask, int remaining) {
		this.orderId = orderId;
		this.orderProductId = orderProductId;
		this.name = name;
		this.filename = filename;
		this.mask = mask;
		this.remaining = remaining;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_download_id", unique = true, nullable = false)
	public Integer getOrderDownloadId() {
		return this.orderDownloadId;
	}

	public void setOrderDownloadId(Integer orderDownloadId) {
		this.orderDownloadId = orderDownloadId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_product_id", nullable = false)
	public int getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(int orderProductId) {
		this.orderProductId = orderProductId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "filename", nullable = false, length = 128)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "mask", nullable = false, length = 128)
	public String getMask() {
		return this.mask;
	}

	public void setMask(String mask) {
		this.mask = mask;
	}

	@Column(name = "remaining", nullable = false)
	public int getRemaining() {
		return this.remaining;
	}

	public void setRemaining(int remaining) {
		this.remaining = remaining;
	}

}
