package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcProductRelatedId generated by hbm2java
 */
@Embeddable
public class ProductRelatedId implements java.io.Serializable {

	private int productId;
	private int relatedId;

	public ProductRelatedId() {
	}

	public ProductRelatedId(int productId, int relatedId) {
		this.productId = productId;
		this.relatedId = relatedId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "related_id", nullable = false)
	public int getRelatedId() {
		return this.relatedId;
	}

	public void setRelatedId(int relatedId) {
		this.relatedId = relatedId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductRelatedId))
			return false;
		ProductRelatedId castOther = (ProductRelatedId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getRelatedId() == castOther.getRelatedId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getRelatedId();
		return result;
	}

}
