package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcProductOptionValue generated by hbm2java
 */
@Entity
@Table(name = "oc_product_option_value", catalog = "opencart")
public class ProductOptionValue implements java.io.Serializable {

	private Integer productOptionValueId;
	private int productOptionId;
	private int productId;
	private int optionId;
	private int optionValueId;
	private int quantity;
	private boolean subtract;
	private BigDecimal price;
	private String pricePrefix;
	private int points;
	private String pointsPrefix;
	private BigDecimal weight;
	private String weightPrefix;

	public ProductOptionValue() {
	}

	public ProductOptionValue(int productOptionId, int productId,
			int optionId, int optionValueId, int quantity, boolean subtract,
			BigDecimal price, String pricePrefix, int points,
			String pointsPrefix, BigDecimal weight, String weightPrefix) {
		this.productOptionId = productOptionId;
		this.productId = productId;
		this.optionId = optionId;
		this.optionValueId = optionValueId;
		this.quantity = quantity;
		this.subtract = subtract;
		this.price = price;
		this.pricePrefix = pricePrefix;
		this.points = points;
		this.pointsPrefix = pointsPrefix;
		this.weight = weight;
		this.weightPrefix = weightPrefix;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_option_value_id", unique = true, nullable = false)
	public Integer getProductOptionValueId() {
		return this.productOptionValueId;
	}

	public void setProductOptionValueId(Integer productOptionValueId) {
		this.productOptionValueId = productOptionValueId;
	}

	@Column(name = "product_option_id", nullable = false)
	public int getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(int productOptionId) {
		this.productOptionId = productOptionId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "option_id", nullable = false)
	public int getOptionId() {
		return this.optionId;
	}

	public void setOptionId(int optionId) {
		this.optionId = optionId;
	}

	@Column(name = "option_value_id", nullable = false)
	public int getOptionValueId() {
		return this.optionValueId;
	}

	public void setOptionValueId(int optionValueId) {
		this.optionValueId = optionValueId;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtract", nullable = false)
	public boolean isSubtract() {
		return this.subtract;
	}

	public void setSubtract(boolean subtract) {
		this.subtract = subtract;
	}

	@Column(name = "price", nullable = false, precision = 15, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "price_prefix", nullable = false, length = 1)
	public String getPricePrefix() {
		return this.pricePrefix;
	}

	public void setPricePrefix(String pricePrefix) {
		this.pricePrefix = pricePrefix;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Column(name = "points_prefix", nullable = false, length = 1)
	public String getPointsPrefix() {
		return this.pointsPrefix;
	}

	public void setPointsPrefix(String pointsPrefix) {
		this.pointsPrefix = pointsPrefix;
	}

	@Column(name = "weight", nullable = false, precision = 15, scale = 8)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "weight_prefix", nullable = false, length = 1)
	public String getWeightPrefix() {
		return this.weightPrefix;
	}

	public void setWeightPrefix(String weightPrefix) {
		this.weightPrefix = weightPrefix;
	}

}
