package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcProductFilterId generated by hbm2java
 */
@Embeddable
public class ProductFilterId implements java.io.Serializable {

	private int productId;
	private int filterId;

	public ProductFilterId() {
	}

	public ProductFilterId(int productId, int filterId) {
		this.productId = productId;
		this.filterId = filterId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "filter_id", nullable = false)
	public int getFilterId() {
		return this.filterId;
	}

	public void setFilterId(int filterId) {
		this.filterId = filterId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductFilterId))
			return false;
		ProductFilterId castOther = (ProductFilterId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getFilterId() == castOther.getFilterId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getFilterId();
		return result;
	}

}
