package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcProductImage generated by hbm2java
 */
@Entity
@Table(name = "oc_product_image", catalog = "opencart")
public class ProductImage implements java.io.Serializable {

	private Integer productImageId;
	private int productId;
	private String image;
	private int sortOrder;

	public ProductImage() {
	}

	public ProductImage(int productId, int sortOrder) {
		this.productId = productId;
		this.sortOrder = sortOrder;
	}

	public ProductImage(int productId, String image, int sortOrder) {
		this.productId = productId;
		this.image = image;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_image_id", unique = true, nullable = false)
	public Integer getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(Integer productImageId) {
		this.productImageId = productImageId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

}
