package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcProductOption generated by hbm2java
 */
@Entity
@Table(name = "oc_product_option", catalog = "opencart")
public class ProductOption implements java.io.Serializable {

	private Integer productOptionId;
	private int productId;
	private int optionId;
	private String optionValue;
	private boolean required;

	public ProductOption() {
	}

	public ProductOption(int productId, int optionId, String optionValue,
			boolean required) {
		this.productId = productId;
		this.optionId = optionId;
		this.optionValue = optionValue;
		this.required = required;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_option_id", unique = true, nullable = false)
	public Integer getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(Integer productOptionId) {
		this.productOptionId = productOptionId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "option_id", nullable = false)
	public int getOptionId() {
		return this.optionId;
	}

	public void setOptionId(int optionId) {
		this.optionId = optionId;
	}

	@Column(name = "option_value", nullable = false, length = 65535)
	public String getOptionValue() {
		return this.optionValue;
	}

	public void setOptionValue(String optionValue) {
		this.optionValue = optionValue;
	}

	@Column(name = "required", nullable = false)
	public boolean isRequired() {
		return this.required;
	}

	public void setRequired(boolean required) {
		this.required = required;
	}

}
