package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcProductToCategory generated by hbm2java
 */
@Entity
@Table(name = "oc_product_to_category", catalog = "opencart")
public class ProductToCategory implements java.io.Serializable {

	private ProductToCategoryId id;

	public ProductToCategory() {
	}

	public ProductToCategory(ProductToCategoryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)) })
	public ProductToCategoryId getId() {
		return this.id;
	}

	public void setId(ProductToCategoryId id) {
		this.id = id;
	}

}
