package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcProductDiscount generated by hbm2java
 */
@Entity
@Table(name = "oc_product_discount", catalog = "opencart")
public class ProductDiscount implements java.io.Serializable {

	private Integer productDiscountId;
	private int productId;
	private int customerGroupId;
	private int quantity;
	private int priority;
	private BigDecimal price;
	private Date dateStart;
	private Date dateEnd;

	public ProductDiscount() {
	}

	public ProductDiscount(int productId, int customerGroupId, int quantity,
			int priority, BigDecimal price, Date dateStart, Date dateEnd) {
		this.productId = productId;
		this.customerGroupId = customerGroupId;
		this.quantity = quantity;
		this.priority = priority;
		this.price = price;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_discount_id", unique = true, nullable = false)
	public Integer getProductDiscountId() {
		return this.productDiscountId;
	}

	public void setProductDiscountId(Integer productDiscountId) {
		this.productDiscountId = productDiscountId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "customer_group_id", nullable = false)
	public int getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(int customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "price", nullable = false, precision = 15, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_start", nullable = false, length = 10)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_end", nullable = false, length = 10)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

}
