package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcProduct generated by hbm2java
 */
@Entity
@Table(name = "oc_product", catalog = "opencart")
public class Product implements java.io.Serializable {

	private Integer productId;
	private String model;
	private String sku;
	private String upc;
	private String ean;
	private String jan;
	private String isbn;
	private String mpn;
	private String location;
	private int quantity;
	private int stockStatusId;
	private String image;
	private int manufacturerId;
	private boolean shipping;
	private BigDecimal price;
	private int points;
	private int taxClassId;
	private Date dateAvailable;
	private BigDecimal weight;
	private int weightClassId;
	private BigDecimal length;
	private BigDecimal width;
	private BigDecimal height;
	private int lengthClassId;
	private boolean subtract;
	private int minimum;
	private int sortOrder;
	private boolean status;
	private Date dateAdded;
	private Date dateModified;
	private int viewed;
	private Integer externalId;

	public Product() {
	}

	public Product(String model, String sku, String upc, String ean,
			String jan, String isbn, String mpn, String location, int quantity,
			int stockStatusId, int manufacturerId, boolean shipping,
			BigDecimal price, int points, int taxClassId, Date dateAvailable,
			BigDecimal weight, int weightClassId, BigDecimal length,
			BigDecimal width, BigDecimal height, int lengthClassId,
			boolean subtract, int minimum, int sortOrder, boolean status,
			Date dateAdded, Date dateModified, int viewed) {
		this.model = model;
		this.sku = sku;
		this.upc = upc;
		this.ean = ean;
		this.jan = jan;
		this.isbn = isbn;
		this.mpn = mpn;
		this.location = location;
		this.quantity = quantity;
		this.stockStatusId = stockStatusId;
		this.manufacturerId = manufacturerId;
		this.shipping = shipping;
		this.price = price;
		this.points = points;
		this.taxClassId = taxClassId;
		this.dateAvailable = dateAvailable;
		this.weight = weight;
		this.weightClassId = weightClassId;
		this.length = length;
		this.width = width;
		this.height = height;
		this.lengthClassId = lengthClassId;
		this.subtract = subtract;
		this.minimum = minimum;
		this.sortOrder = sortOrder;
		this.status = status;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
		this.viewed = viewed;
	}

	public Product(String model, String sku, String upc, String ean,
			String jan, String isbn, String mpn, String location, int quantity,
			int stockStatusId, String image, int manufacturerId,
			boolean shipping, BigDecimal price, int points, int taxClassId,
			Date dateAvailable, BigDecimal weight, int weightClassId,
			BigDecimal length, BigDecimal width, BigDecimal height,
			int lengthClassId, boolean subtract, int minimum, int sortOrder,
			boolean status, Date dateAdded, Date dateModified, int viewed,
			Integer externalId) {
		this.model = model;
		this.sku = sku;
		this.upc = upc;
		this.ean = ean;
		this.jan = jan;
		this.isbn = isbn;
		this.mpn = mpn;
		this.location = location;
		this.quantity = quantity;
		this.stockStatusId = stockStatusId;
		this.image = image;
		this.manufacturerId = manufacturerId;
		this.shipping = shipping;
		this.price = price;
		this.points = points;
		this.taxClassId = taxClassId;
		this.dateAvailable = dateAvailable;
		this.weight = weight;
		this.weightClassId = weightClassId;
		this.length = length;
		this.width = width;
		this.height = height;
		this.lengthClassId = lengthClassId;
		this.subtract = subtract;
		this.minimum = minimum;
		this.sortOrder = sortOrder;
		this.status = status;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
		this.viewed = viewed;
		this.externalId = externalId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "model", nullable = false, length = 64)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "sku", nullable = false, length = 64)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "upc", nullable = false, length = 12)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "ean", nullable = false, length = 14)
	public String getEan() {
		return this.ean;
	}

	public void setEan(String ean) {
		this.ean = ean;
	}

	@Column(name = "jan", nullable = false, length = 13)
	public String getJan() {
		return this.jan;
	}

	public void setJan(String jan) {
		this.jan = jan;
	}

	@Column(name = "isbn", nullable = false, length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "mpn", nullable = false, length = 64)
	public String getMpn() {
		return this.mpn;
	}

	public void setMpn(String mpn) {
		this.mpn = mpn;
	}

	@Column(name = "location", nullable = false, length = 128)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "stock_status_id", nullable = false)
	public int getStockStatusId() {
		return this.stockStatusId;
	}

	public void setStockStatusId(int stockStatusId) {
		this.stockStatusId = stockStatusId;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "manufacturer_id", nullable = false)
	public int getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(int manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "shipping", nullable = false)
	public boolean isShipping() {
		return this.shipping;
	}

	public void setShipping(boolean shipping) {
		this.shipping = shipping;
	}

	@Column(name = "price", nullable = false, precision = 15, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	@Column(name = "tax_class_id", nullable = false)
	public int getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(int taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_available", nullable = false, length = 10)
	public Date getDateAvailable() {
		return this.dateAvailable;
	}

	public void setDateAvailable(Date dateAvailable) {
		this.dateAvailable = dateAvailable;
	}

	@Column(name = "weight", nullable = false, precision = 15, scale = 8)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "weight_class_id", nullable = false)
	public int getWeightClassId() {
		return this.weightClassId;
	}

	public void setWeightClassId(int weightClassId) {
		this.weightClassId = weightClassId;
	}

	@Column(name = "length", nullable = false, precision = 15, scale = 8)
	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	@Column(name = "width", nullable = false, precision = 15, scale = 8)
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false, precision = 15, scale = 8)
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	@Column(name = "length_class_id", nullable = false)
	public int getLengthClassId() {
		return this.lengthClassId;
	}

	public void setLengthClassId(int lengthClassId) {
		this.lengthClassId = lengthClassId;
	}

	@Column(name = "subtract", nullable = false)
	public boolean isSubtract() {
		return this.subtract;
	}

	public void setSubtract(boolean subtract) {
		this.subtract = subtract;
	}

	@Column(name = "minimum", nullable = false)
	public int getMinimum() {
		return this.minimum;
	}

	public void setMinimum(int minimum) {
		this.minimum = minimum;
	}

	@Column(name = "sort_order", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "viewed", nullable = false)
	public int getViewed() {
		return this.viewed;
	}

	public void setViewed(int viewed) {
		this.viewed = viewed;
	}

	@Column(name = "external_id")
	public Integer getExternalId() {
		return this.externalId;
	}

	public void setExternalId(Integer externalId) {
		this.externalId = externalId;
	}

}
