package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcProductDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_product_description", catalog = "opencart")
public class ProductDescription implements java.io.Serializable {

	private ProductDescriptionId id;
	private String name;
	private String description;
	private String metaDescription;
	private String metaKeyword;
	private String tag;

	public ProductDescription() {
	}

	public ProductDescription(ProductDescriptionId id, String name,
			String description, String metaDescription, String metaKeyword,
			String tag) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.metaDescription = metaDescription;
		this.metaKeyword = metaKeyword;
		this.tag = tag;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public ProductDescriptionId getId() {
		return this.id;
	}

	public void setId(ProductDescriptionId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "meta_description", nullable = false)
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	@Column(name = "meta_keyword", nullable = false)
	public String getMetaKeyword() {
		return this.metaKeyword;
	}

	public void setMetaKeyword(String metaKeyword) {
		this.metaKeyword = metaKeyword;
	}

	@Column(name = "tag", nullable = false, length = 65535)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
