package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcProductFilter generated by hbm2java
 */
@Entity
@Table(name = "oc_product_filter", catalog = "opencart")
public class ProductFilter implements java.io.Serializable {

	private ProductFilterId id;

	public ProductFilter() {
	}

	public ProductFilter(ProductFilterId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "filterId", column = @Column(name = "filter_id", nullable = false)) })
	public ProductFilterId getId() {
		return this.id;
	}

	public void setId(ProductFilterId id) {
		this.id = id;
	}

}
