package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcReturnStatus generated by hbm2java
 */
@Entity
@Table(name = "oc_return_status", catalog = "opencart")
public class ReturnStatus implements java.io.Serializable {

	private ReturnStatusId id;
	private String name;

	public ReturnStatus() {
	}

	public ReturnStatus(ReturnStatusId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "returnStatusId", column = @Column(name = "return_status_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public ReturnStatusId getId() {
		return this.id;
	}

	public void setId(ReturnStatusId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
