package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcReturnReason generated by hbm2java
 */
@Entity
@Table(name = "oc_return_reason", catalog = "opencart")
public class ReturnReason implements java.io.Serializable {

	private ReturnReasonId id;
	private String name;

	public ReturnReason() {
	}

	public ReturnReason(ReturnReasonId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "returnReasonId", column = @Column(name = "return_reason_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public ReturnReasonId getId() {
		return this.id;
	}

	public void setId(ReturnReasonId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
