package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcReturn generated by hbm2java
 */
@Entity
@Table(name = "oc_return", catalog = "opencart")
public class Return implements java.io.Serializable {

	private Integer returnId;
	private int orderId;
	private int productId;
	private int customerId;
	private String firstname;
	private String lastname;
	private String email;
	private String telephone;
	private String product;
	private String model;
	private int quantity;
	private boolean opened;
	private int returnReasonId;
	private int returnActionId;
	private int returnStatusId;
	private String comment;
	private Date dateOrdered;
	private Date dateAdded;
	private Date dateModified;

	public Return() {
	}

	public Return(int orderId, int productId, int customerId,
			String firstname, String lastname, String email, String telephone,
			String product, String model, int quantity, boolean opened,
			int returnReasonId, int returnActionId, int returnStatusId,
			Date dateOrdered, Date dateAdded, Date dateModified) {
		this.orderId = orderId;
		this.productId = productId;
		this.customerId = customerId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.telephone = telephone;
		this.product = product;
		this.model = model;
		this.quantity = quantity;
		this.opened = opened;
		this.returnReasonId = returnReasonId;
		this.returnActionId = returnActionId;
		this.returnStatusId = returnStatusId;
		this.dateOrdered = dateOrdered;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
	}

	public Return(int orderId, int productId, int customerId,
			String firstname, String lastname, String email, String telephone,
			String product, String model, int quantity, boolean opened,
			int returnReasonId, int returnActionId, int returnStatusId,
			String comment, Date dateOrdered, Date dateAdded, Date dateModified) {
		this.orderId = orderId;
		this.productId = productId;
		this.customerId = customerId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.telephone = telephone;
		this.product = product;
		this.model = model;
		this.quantity = quantity;
		this.opened = opened;
		this.returnReasonId = returnReasonId;
		this.returnActionId = returnActionId;
		this.returnStatusId = returnStatusId;
		this.comment = comment;
		this.dateOrdered = dateOrdered;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "return_id", unique = true, nullable = false)
	public Integer getReturnId() {
		return this.returnId;
	}

	public void setReturnId(Integer returnId) {
		this.returnId = returnId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "firstname", nullable = false, length = 32)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 32)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 96)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", nullable = false, length = 32)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "product", nullable = false)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "model", nullable = false, length = 64)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "opened", nullable = false)
	public boolean isOpened() {
		return this.opened;
	}

	public void setOpened(boolean opened) {
		this.opened = opened;
	}

	@Column(name = "return_reason_id", nullable = false)
	public int getReturnReasonId() {
		return this.returnReasonId;
	}

	public void setReturnReasonId(int returnReasonId) {
		this.returnReasonId = returnReasonId;
	}

	@Column(name = "return_action_id", nullable = false)
	public int getReturnActionId() {
		return this.returnActionId;
	}

	public void setReturnActionId(int returnActionId) {
		this.returnActionId = returnActionId;
	}

	@Column(name = "return_status_id", nullable = false)
	public int getReturnStatusId() {
		return this.returnStatusId;
	}

	public void setReturnStatusId(int returnStatusId) {
		this.returnStatusId = returnStatusId;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ordered", nullable = false, length = 10)
	public Date getDateOrdered() {
		return this.dateOrdered;
	}

	public void setDateOrdered(Date dateOrdered) {
		this.dateOrdered = dateOrdered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
