package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcReturnStatusId generated by hbm2java
 */
@Embeddable
public class ReturnStatusId implements java.io.Serializable {

	private int returnStatusId;
	private int languageId;

	public ReturnStatusId() {
	}

	public ReturnStatusId(int returnStatusId, int languageId) {
		this.returnStatusId = returnStatusId;
		this.languageId = languageId;
	}

	@Column(name = "return_status_id", nullable = false)
	public int getReturnStatusId() {
		return this.returnStatusId;
	}

	public void setReturnStatusId(int returnStatusId) {
		this.returnStatusId = returnStatusId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReturnStatusId))
			return false;
		ReturnStatusId castOther = (ReturnStatusId) other;

		return (this.getReturnStatusId() == castOther.getReturnStatusId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReturnStatusId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
