package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcSetting generated by hbm2java
 */
@Entity
@Table(name = "oc_setting", catalog = "opencart")
public class Setting implements java.io.Serializable {

	private Integer settingId;
	private int storeId;
	private String group;
	private String key;
	private String value;
	private boolean serialized;

	public Setting() {
	}

	public Setting(int storeId, String group, String key, String value,
			boolean serialized) {
		this.storeId = storeId;
		this.group = group;
		this.key = key;
		this.value = value;
		this.serialized = serialized;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "setting_id", unique = true, nullable = false)
	public Integer getSettingId() {
		return this.settingId;
	}

	public void setSettingId(Integer settingId) {
		this.settingId = settingId;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@Column(name = "group", nullable = false, length = 32)
	public String getGroup() {
		return this.group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	@Column(name = "key", nullable = false, length = 64)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "serialized", nullable = false)
	public boolean isSerialized() {
		return this.serialized;
	}

	public void setSerialized(boolean serialized) {
		this.serialized = serialized;
	}

}
