package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcStockStatusId generated by hbm2java
 */
@Embeddable
public class StockStatusId implements java.io.Serializable {

	private int stockStatusId;
	private int languageId;

	public StockStatusId() {
	}

	public StockStatusId(int stockStatusId, int languageId) {
		this.stockStatusId = stockStatusId;
		this.languageId = languageId;
	}

	@Column(name = "stock_status_id", nullable = false)
	public int getStockStatusId() {
		return this.stockStatusId;
	}

	public void setStockStatusId(int stockStatusId) {
		this.stockStatusId = stockStatusId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockStatusId))
			return false;
		StockStatusId castOther = (StockStatusId) other;

		return (this.getStockStatusId() == castOther.getStockStatusId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStockStatusId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
