package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcStore generated by hbm2java
 */
@Entity
@Table(name = "oc_store", catalog = "opencart")
public class Store implements java.io.Serializable {

	private Integer storeId;
	private String name;
	private String url;
	private String ssl;

	public Store() {
	}

	public Store(String name, String url, String ssl) {
		this.name = name;
		this.url = url;
		this.ssl = ssl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "store_id", unique = true, nullable = false)
	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ssl", nullable = false)
	public String getSsl() {
		return this.ssl;
	}

	public void setSsl(String ssl) {
		this.ssl = ssl;
	}

}
