package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcTaxClass generated by hbm2java
 */
@Entity
@Table(name = "oc_tax_class", catalog = "opencart")
public class TaxClass implements java.io.Serializable {

	private Integer taxClassId;
	private String title;
	private String description;
	private Date dateAdded;
	private Date dateModified;

	public TaxClass() {
	}

	public TaxClass(String title, String description, Date dateAdded,
			Date dateModified) {
		this.title = title;
		this.description = description;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tax_class_id", unique = true, nullable = false)
	public Integer getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Integer taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Column(name = "title", nullable = false, length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
