package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcTaxRateToCustomerGroupId generated by hbm2java
 */
@Embeddable
public class TaxRateToCustomerGroupId implements java.io.Serializable {

	private int taxRateId;
	private int customerGroupId;

	public TaxRateToCustomerGroupId() {
	}

	public TaxRateToCustomerGroupId(int taxRateId, int customerGroupId) {
		this.taxRateId = taxRateId;
		this.customerGroupId = customerGroupId;
	}

	@Column(name = "tax_rate_id", nullable = false)
	public int getTaxRateId() {
		return this.taxRateId;
	}

	public void setTaxRateId(int taxRateId) {
		this.taxRateId = taxRateId;
	}

	@Column(name = "customer_group_id", nullable = false)
	public int getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(int customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaxRateToCustomerGroupId))
			return false;
		TaxRateToCustomerGroupId castOther = (TaxRateToCustomerGroupId) other;

		return (this.getTaxRateId() == castOther.getTaxRateId())
				&& (this.getCustomerGroupId() == castOther.getCustomerGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTaxRateId();
		result = 37 * result + this.getCustomerGroupId();
		return result;
	}

}
