package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcTaxRule generated by hbm2java
 */
@Entity
@Table(name = "oc_tax_rule", catalog = "opencart")
public class TaxRule implements java.io.Serializable {

	private Integer taxRuleId;
	private int taxClassId;
	private int taxRateId;
	private String based;
	private int priority;

	public TaxRule() {
	}

	public TaxRule(int taxClassId, int taxRateId, String based, int priority) {
		this.taxClassId = taxClassId;
		this.taxRateId = taxRateId;
		this.based = based;
		this.priority = priority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tax_rule_id", unique = true, nullable = false)
	public Integer getTaxRuleId() {
		return this.taxRuleId;
	}

	public void setTaxRuleId(Integer taxRuleId) {
		this.taxRuleId = taxRuleId;
	}

	@Column(name = "tax_class_id", nullable = false)
	public int getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(int taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Column(name = "tax_rate_id", nullable = false)
	public int getTaxRateId() {
		return this.taxRateId;
	}

	public void setTaxRateId(int taxRateId) {
		this.taxRateId = taxRateId;
	}

	@Column(name = "based", nullable = false, length = 10)
	public String getBased() {
		return this.based;
	}

	public void setBased(String based) {
		this.based = based;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
