package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcTaxRate generated by hbm2java
 */
@Entity
@Table(name = "oc_tax_rate", catalog = "opencart")
public class TaxRate implements java.io.Serializable {

	private Integer taxRateId;
	private int geoZoneId;
	private String name;
	private BigDecimal rate;
	private char type;
	private Date dateAdded;
	private Date dateModified;

	public TaxRate() {
	}

	public TaxRate(int geoZoneId, String name, BigDecimal rate, char type,
			Date dateAdded, Date dateModified) {
		this.geoZoneId = geoZoneId;
		this.name = name;
		this.rate = rate;
		this.type = type;
		this.dateAdded = dateAdded;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tax_rate_id", unique = true, nullable = false)
	public Integer getTaxRateId() {
		return this.taxRateId;
	}

	public void setTaxRateId(Integer taxRateId) {
		this.taxRateId = taxRateId;
	}

	@Column(name = "geo_zone_id", nullable = false)
	public int getGeoZoneId() {
		return this.geoZoneId;
	}

	public void setGeoZoneId(int geoZoneId) {
		this.geoZoneId = geoZoneId;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rate", nullable = false, precision = 15, scale = 4)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 19)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
