package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcTaxRateToCustomerGroup generated by hbm2java
 */
@Entity
@Table(name = "oc_tax_rate_to_customer_group", catalog = "opencart")
public class TaxRateToCustomerGroup implements java.io.Serializable {

	private TaxRateToCustomerGroupId id;

	public TaxRateToCustomerGroup() {
	}

	public TaxRateToCustomerGroup(TaxRateToCustomerGroupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "taxRateId", column = @Column(name = "tax_rate_id", nullable = false)),
			@AttributeOverride(name = "customerGroupId", column = @Column(name = "customer_group_id", nullable = false)) })
	public TaxRateToCustomerGroupId getId() {
		return this.id;
	}

	public void setId(TaxRateToCustomerGroupId id) {
		this.id = id;
	}

}
