package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcUrlAlias generated by hbm2java
 */
@Entity
@Table(name = "oc_url_alias", catalog = "opencart")
public class UrlAlias implements java.io.Serializable {

	private Integer urlAliasId;
	private String query;
	private String keyword;

	public UrlAlias() {
	}

	public UrlAlias(String query, String keyword) {
		this.query = query;
		this.keyword = keyword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "url_alias_id", unique = true, nullable = false)
	public Integer getUrlAliasId() {
		return this.urlAliasId;
	}

	public void setUrlAliasId(Integer urlAliasId) {
		this.urlAliasId = urlAliasId;
	}

	@Column(name = "query", nullable = false)
	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	@Column(name = "keyword", nullable = false)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
