package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcVoucherThemeDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_voucher_theme_description", catalog = "opencart")
public class VoucherThemeDescription implements java.io.Serializable {

	private VoucherThemeDescriptionId id;
	private String name;

	public VoucherThemeDescription() {
	}

	public VoucherThemeDescription(VoucherThemeDescriptionId id, String name) {
		this.id = id;
		this.name = name;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "voucherThemeId", column = @Column(name = "voucher_theme_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public VoucherThemeDescriptionId getId() {
		return this.id;
	}

	public void setId(VoucherThemeDescriptionId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
