package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcVoucherTheme generated by hbm2java
 */
@Entity
@Table(name = "oc_voucher_theme", catalog = "opencart")
public class VoucherTheme implements java.io.Serializable {

	private Integer voucherThemeId;
	private String image;

	public VoucherTheme() {
	}

	public VoucherTheme(String image) {
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "voucher_theme_id", unique = true, nullable = false)
	public Integer getVoucherThemeId() {
		return this.voucherThemeId;
	}

	public void setVoucherThemeId(Integer voucherThemeId) {
		this.voucherThemeId = voucherThemeId;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
