package com.cherkashyn.vitalii.computer_shop.opencart.domain;

// Generated Sep 27, 2013 3:55:56 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcWeightClassDescription generated by hbm2java
 */
@Entity
@Table(name = "oc_weight_class_description", catalog = "opencart")
public class WeightClassDescription implements java.io.Serializable {

	private WeightClassDescriptionId id;
	private String title;
	private String unit;

	public WeightClassDescription() {
	}

	public WeightClassDescription(WeightClassDescriptionId id,
			String title, String unit) {
		this.id = id;
		this.title = title;
		this.unit = unit;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "weightClassId", column = @Column(name = "weight_class_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public WeightClassDescriptionId getId() {
		return this.id;
	}

	public void setId(WeightClassDescriptionId id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "unit", nullable = false, length = 4)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
