// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.cherkashyn.vitaliy.protobuf.exchange;

public final class ElementWorker {
  private ElementWorker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Worker extends
      com.google.protobuf.GeneratedMessage {
    // Use Worker.newBuilder() to construct.
    private Worker() {}
    
    private static final Worker defaultInstance = new Worker();
    public static Worker getDefaultInstance() {
      return defaultInstance;
    }
    
    public Worker getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Worker_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Worker_fieldAccessorTable;
    }
    
    public static final class Address extends
        com.google.protobuf.GeneratedMessage {
      // Use Address.newBuilder() to construct.
      private Address() {}
      
      private static final Address defaultInstance = new Address();
      public static Address getDefaultInstance() {
        return defaultInstance;
      }
      
      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Worker_Address_descriptor;
      }
      
      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Worker_Address_fieldAccessorTable;
      }
      
      // required int32 post_index = 1;
      public static final int POST_INDEX_FIELD_NUMBER = 1;
      private boolean hasPostIndex;
      private int postIndex_ = 0;
      public boolean hasPostIndex() { return hasPostIndex; }
      public int getPostIndex() { return postIndex_; }
      
      // required string city = 2;
      public static final int CITY_FIELD_NUMBER = 2;
      private boolean hasCity;
      private java.lang.String city_ = "";
      public boolean hasCity() { return hasCity; }
      public java.lang.String getCity() { return city_; }
      
      // required string street = 3;
      public static final int STREET_FIELD_NUMBER = 3;
      private boolean hasStreet;
      private java.lang.String street_ = "";
      public boolean hasStreet() { return hasStreet; }
      public java.lang.String getStreet() { return street_; }
      
      // required int32 b_number = 4;
      public static final int B_NUMBER_FIELD_NUMBER = 4;
      private boolean hasBNumber;
      private int bNumber_ = 0;
      public boolean hasBNumber() { return hasBNumber; }
      public int getBNumber() { return bNumber_; }
      
      // optional string b_number_add = 5;
      public static final int B_NUMBER_ADD_FIELD_NUMBER = 5;
      private boolean hasBNumberAdd;
      private java.lang.String bNumberAdd_ = "";
      public boolean hasBNumberAdd() { return hasBNumberAdd; }
      public java.lang.String getBNumberAdd() { return bNumberAdd_; }
      
      // optional int32 flat_number = 6;
      public static final int FLAT_NUMBER_FIELD_NUMBER = 6;
      private boolean hasFlatNumber;
      private int flatNumber_ = 0;
      public boolean hasFlatNumber() { return hasFlatNumber; }
      public int getFlatNumber() { return flatNumber_; }
      
      @Override
      public final boolean isInitialized() {
        if (!hasPostIndex) return false;
        if (!hasCity) return false;
        if (!hasStreet) return false;
        if (!hasBNumber) return false;
        return true;
      }
      
      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasPostIndex()) {
          output.writeInt32(1, getPostIndex());
        }
        if (hasCity()) {
          output.writeString(2, getCity());
        }
        if (hasStreet()) {
          output.writeString(3, getStreet());
        }
        if (hasBNumber()) {
          output.writeInt32(4, getBNumber());
        }
        if (hasBNumberAdd()) {
          output.writeString(5, getBNumberAdd());
        }
        if (hasFlatNumber()) {
          output.writeInt32(6, getFlatNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      @Override
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasPostIndex()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getPostIndex());
        }
        if (hasCity()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getCity());
        }
        if (hasStreet()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getStreet());
        }
        if (hasBNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, getBNumber());
        }
        if (hasBNumberAdd()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(5, getBNumberAdd());
        }
        if (hasFlatNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, getFlatNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address prototype) {
        return new Builder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.newBuilder()
        private Builder() {}
        
        com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address();
        
        @Override
        protected com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address internalGetResult() {
          return result;
        }
        
        @Override
        public Builder clear() {
          result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address();
          return this;
        }
        
        @Override
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDescriptor();
        }
        
        public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address getDefaultInstanceForType() {
          return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance();
        }
        
        public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address build() {
          if (result != null && !isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");  }
          com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address returnMe = result;
          result = null;
          return returnMe;
        }
        
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address) {
            return mergeFrom((com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address other) {
          if (other == com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance()) return this;
          if (other.hasPostIndex()) {
            setPostIndex(other.getPostIndex());
          }
          if (other.hasCity()) {
            setCity(other.getCity());
          }
          if (other.hasStreet()) {
            setStreet(other.getStreet());
          }
          if (other.hasBNumber()) {
            setBNumber(other.getBNumber());
          }
          if (other.hasBNumberAdd()) {
            setBNumberAdd(other.getBNumberAdd());
          }
          if (other.hasFlatNumber()) {
            setFlatNumber(other.getFlatNumber());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return mergeFrom(input,
            com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
        }
        
        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistry extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setPostIndex(input.readInt32());
                break;
              }
              case 18: {
                setCity(input.readString());
                break;
              }
              case 26: {
                setStreet(input.readString());
                break;
              }
              case 32: {
                setBNumber(input.readInt32());
                break;
              }
              case 42: {
                setBNumberAdd(input.readString());
                break;
              }
              case 48: {
                setFlatNumber(input.readInt32());
                break;
              }
            }
          }
        }
        
        
        // required int32 post_index = 1;
        public boolean hasPostIndex() {
          return result.hasPostIndex();
        }
        public int getPostIndex() {
          return result.getPostIndex();
        }
        public Builder setPostIndex(int value) {
          result.hasPostIndex = true;
          result.postIndex_ = value;
          return this;
        }
        public Builder clearPostIndex() {
          result.hasPostIndex = false;
          result.postIndex_ = 0;
          return this;
        }
        
        // required string city = 2;
        public boolean hasCity() {
          return result.hasCity();
        }
        public java.lang.String getCity() {
          return result.getCity();
        }
        public Builder setCity(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasCity = true;
          result.city_ = value;
          return this;
        }
        public Builder clearCity() {
          result.hasCity = false;
          result.city_ = "";
          return this;
        }
        
        // required string street = 3;
        public boolean hasStreet() {
          return result.hasStreet();
        }
        public java.lang.String getStreet() {
          return result.getStreet();
        }
        public Builder setStreet(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasStreet = true;
          result.street_ = value;
          return this;
        }
        public Builder clearStreet() {
          result.hasStreet = false;
          result.street_ = "";
          return this;
        }
        
        // required int32 b_number = 4;
        public boolean hasBNumber() {
          return result.hasBNumber();
        }
        public int getBNumber() {
          return result.getBNumber();
        }
        public Builder setBNumber(int value) {
          result.hasBNumber = true;
          result.bNumber_ = value;
          return this;
        }
        public Builder clearBNumber() {
          result.hasBNumber = false;
          result.bNumber_ = 0;
          return this;
        }
        
        // optional string b_number_add = 5;
        public boolean hasBNumberAdd() {
          return result.hasBNumberAdd();
        }
        public java.lang.String getBNumberAdd() {
          return result.getBNumberAdd();
        }
        public Builder setBNumberAdd(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasBNumberAdd = true;
          result.bNumberAdd_ = value;
          return this;
        }
        public Builder clearBNumberAdd() {
          result.hasBNumberAdd = false;
          result.bNumberAdd_ = "";
          return this;
        }
        
        // optional int32 flat_number = 6;
        public boolean hasFlatNumber() {
          return result.hasFlatNumber();
        }
        public int getFlatNumber() {
          return result.getFlatNumber();
        }
        public Builder setFlatNumber(int value) {
          result.hasFlatNumber = true;
          result.flatNumber_ = value;
          return this;
        }
        public Builder clearFlatNumber() {
          result.hasFlatNumber = false;
          result.flatNumber_ = 0;
          return this;
        }
      }
      
      static {
        com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.getDescriptor();
      }
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required string name_first = 2;
    public static final int NAME_FIRST_FIELD_NUMBER = 2;
    private boolean hasNameFirst;
    private java.lang.String nameFirst_ = "";
    public boolean hasNameFirst() { return hasNameFirst; }
    public java.lang.String getNameFirst() { return nameFirst_; }
    
    // required string name_second = 3;
    public static final int NAME_SECOND_FIELD_NUMBER = 3;
    private boolean hasNameSecond;
    private java.lang.String nameSecond_ = "";
    public boolean hasNameSecond() { return hasNameSecond; }
    public java.lang.String getNameSecond() { return nameSecond_; }
    
    // optional string phone = 4;
    public static final int PHONE_FIELD_NUMBER = 4;
    private boolean hasPhone;
    private java.lang.String phone_ = "";
    public boolean hasPhone() { return hasPhone; }
    public java.lang.String getPhone() { return phone_; }
    
    // repeated .tutorial.Position positions = 5;
    public static final int POSITIONS_FIELD_NUMBER = 5;
    private java.util.List<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position> positions_ =
      java.util.Collections.emptyList();
    public java.util.List<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position> getPositionsList() {
      return positions_;
    }
    public int getPositionsCount() { return positions_.size(); }
    public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position getPositions(int index) {
      return positions_.get(index);
    }
    
    // optional .tutorial.Worker.Address home_address = 6;
    public static final int HOME_ADDRESS_FIELD_NUMBER = 6;
    private boolean hasHomeAddress;
    private com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address homeAddress_ = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance();
    public boolean hasHomeAddress() { return hasHomeAddress; }
    public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address getHomeAddress() { return homeAddress_; }
    
    // optional .tutorial.Worker.Address work_address = 7;
    public static final int WORK_ADDRESS_FIELD_NUMBER = 7;
    private boolean hasWorkAddress;
    private com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address workAddress_ = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance();
    public boolean hasWorkAddress() { return hasWorkAddress; }
    public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address getWorkAddress() { return workAddress_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasNameFirst) return false;
      if (!hasNameSecond) return false;
      for (com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position element : getPositionsList()) {
        if (!element.isInitialized()) return false;
      }
      if (hasHomeAddress()) {
        if (!getHomeAddress().isInitialized()) return false;
      }
      if (hasWorkAddress()) {
        if (!getWorkAddress().isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasNameFirst()) {
        output.writeString(2, getNameFirst());
      }
      if (hasNameSecond()) {
        output.writeString(3, getNameSecond());
      }
      if (hasPhone()) {
        output.writeString(4, getPhone());
      }
      for (com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position element : getPositionsList()) {
        output.writeMessage(5, element);
      }
      if (hasHomeAddress()) {
        output.writeMessage(6, getHomeAddress());
      }
      if (hasWorkAddress()) {
        output.writeMessage(7, getWorkAddress());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasNameFirst()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNameFirst());
      }
      if (hasNameSecond()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNameSecond());
      }
      if (hasPhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPhone());
      }
      for (com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position element : getPositionsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      if (hasHomeAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getHomeAddress());
      }
      if (hasWorkAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getWorkAddress());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.newBuilder()
      private Builder() {}
      
      com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker();
      
      @Override
      protected com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.getDescriptor();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker getDefaultInstanceForType() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.getDefaultInstance();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.positions_ != java.util.Collections.EMPTY_LIST) {
          result.positions_ =
            java.util.Collections.unmodifiableList(result.positions_);
        }
        com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker) {
          return mergeFrom((com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker other) {
        if (other == com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNameFirst()) {
          setNameFirst(other.getNameFirst());
        }
        if (other.hasNameSecond()) {
          setNameSecond(other.getNameSecond());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (!other.positions_.isEmpty()) {
          if (result.positions_.isEmpty()) {
            result.positions_ = new java.util.ArrayList<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position>();
          }
          result.positions_.addAll(other.positions_);
        }
        if (other.hasHomeAddress()) {
          mergeHomeAddress(other.getHomeAddress());
        }
        if (other.hasWorkAddress()) {
          mergeWorkAddress(other.getWorkAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setNameFirst(input.readString());
              break;
            }
            case 26: {
              setNameSecond(input.readString());
              break;
            }
            case 34: {
              setPhone(input.readString());
              break;
            }
            case 42: {
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.Builder subBuilder = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPositions(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.Builder subBuilder = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.newBuilder();
              if (hasHomeAddress()) {
                subBuilder.mergeFrom(getHomeAddress());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHomeAddress(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.Builder subBuilder = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.newBuilder();
              if (hasWorkAddress()) {
                subBuilder.mergeFrom(getWorkAddress());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setWorkAddress(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required string name_first = 2;
      public boolean hasNameFirst() {
        return result.hasNameFirst();
      }
      public java.lang.String getNameFirst() {
        return result.getNameFirst();
      }
      public Builder setNameFirst(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNameFirst = true;
        result.nameFirst_ = value;
        return this;
      }
      public Builder clearNameFirst() {
        result.hasNameFirst = false;
        result.nameFirst_ = "";
        return this;
      }
      
      // required string name_second = 3;
      public boolean hasNameSecond() {
        return result.hasNameSecond();
      }
      public java.lang.String getNameSecond() {
        return result.getNameSecond();
      }
      public Builder setNameSecond(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNameSecond = true;
        result.nameSecond_ = value;
        return this;
      }
      public Builder clearNameSecond() {
        result.hasNameSecond = false;
        result.nameSecond_ = "";
        return this;
      }
      
      // optional string phone = 4;
      public boolean hasPhone() {
        return result.hasPhone();
      }
      public java.lang.String getPhone() {
        return result.getPhone();
      }
      public Builder setPhone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhone = true;
        result.phone_ = value;
        return this;
      }
      public Builder clearPhone() {
        result.hasPhone = false;
        result.phone_ = "";
        return this;
      }
      
      // repeated .tutorial.Position positions = 5;
      public java.util.List<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position> getPositionsList() {
        return java.util.Collections.unmodifiableList(result.positions_);
      }
      public int getPositionsCount() {
        return result.getPositionsCount();
      }
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position getPositions(int index) {
        return result.getPositions(index);
      }
      public Builder setPositions(int index, com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.positions_.set(index, value);
        return this;
      }
      public Builder setPositions(int index, com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.Builder builderForValue) {
        result.positions_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPositions(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.positions_.isEmpty()) {
          result.positions_ = new java.util.ArrayList<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position>();
        }
        result.positions_.add(value);
        return this;
      }
      public Builder addPositions(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.Builder builderForValue) {
        if (result.positions_.isEmpty()) {
          result.positions_ = new java.util.ArrayList<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position>();
        }
        result.positions_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPositions(
          java.lang.Iterable<? extends com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position> values) {
        if (result.positions_.isEmpty()) {
          result.positions_ = new java.util.ArrayList<com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position>();
        }
        super.addAll(values, result.positions_);
        return this;
      }
      public Builder clearPositions() {
        result.positions_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .tutorial.Worker.Address home_address = 6;
      public boolean hasHomeAddress() {
        return result.hasHomeAddress();
      }
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address getHomeAddress() {
        return result.getHomeAddress();
      }
      public Builder setHomeAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasHomeAddress = true;
        result.homeAddress_ = value;
        return this;
      }
      public Builder setHomeAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.Builder builderForValue) {
        result.hasHomeAddress = true;
        result.homeAddress_ = builderForValue.build();
        return this;
      }
      public Builder mergeHomeAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address value) {
        if (result.hasHomeAddress() &&
            result.homeAddress_ != com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance()) {
          result.homeAddress_ =
            com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.newBuilder(result.homeAddress_).mergeFrom(value).buildPartial();
        } else {
          result.homeAddress_ = value;
        }
        result.hasHomeAddress = true;
        return this;
      }
      public Builder clearHomeAddress() {
        result.hasHomeAddress = false;
        result.homeAddress_ = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance();
        return this;
      }
      
      // optional .tutorial.Worker.Address work_address = 7;
      public boolean hasWorkAddress() {
        return result.hasWorkAddress();
      }
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address getWorkAddress() {
        return result.getWorkAddress();
      }
      public Builder setWorkAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasWorkAddress = true;
        result.workAddress_ = value;
        return this;
      }
      public Builder setWorkAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.Builder builderForValue) {
        result.hasWorkAddress = true;
        result.workAddress_ = builderForValue.build();
        return this;
      }
      public Builder mergeWorkAddress(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address value) {
        if (result.hasWorkAddress() &&
            result.workAddress_ != com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance()) {
          result.workAddress_ =
            com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.newBuilder(result.workAddress_).mergeFrom(value).buildPartial();
        } else {
          result.workAddress_ = value;
        }
        result.hasWorkAddress = true;
        return this;
      }
      public Builder clearWorkAddress() {
        result.hasWorkAddress = false;
        result.workAddress_ = com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.getDefaultInstance();
        return this;
      }
    }
    
    static {
      com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.getDescriptor();
    }
  }
  
  public static final class Position extends
      com.google.protobuf.GeneratedMessage {
    // Use Position.newBuilder() to construct.
    private Position() {}
    
    private static final Position defaultInstance = new Position();
    public static Position getDefaultInstance() {
      return defaultInstance;
    }
    
    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Position_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.internal_static_tutorial_Position_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required float salary = 2;
    public static final int SALARY_FIELD_NUMBER = 2;
    private boolean hasSalary;
    private float salary_ = 0F;
    public boolean hasSalary() { return hasSalary; }
    public float getSalary() { return salary_; }
    
    // required string position_name = 3;
    public static final int POSITION_NAME_FIELD_NUMBER = 3;
    private boolean hasPositionName;
    private java.lang.String positionName_ = "";
    public boolean hasPositionName() { return hasPositionName; }
    public java.lang.String getPositionName() { return positionName_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasSalary) return false;
      if (!hasPositionName) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasSalary()) {
        output.writeFloat(2, getSalary());
      }
      if (hasPositionName()) {
        output.writeString(3, getPositionName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasSalary()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getSalary());
      }
      if (hasPositionName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPositionName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.newBuilder()
      private Builder() {}
      
      com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position();
      
      @Override
      protected com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.getDescriptor();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position getDefaultInstanceForType() {
        return com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.getDefaultInstance();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position) {
          return mergeFrom((com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position other) {
        if (other == com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        if (other.hasPositionName()) {
          setPositionName(other.getPositionName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 21: {
              setSalary(input.readFloat());
              break;
            }
            case 26: {
              setPositionName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required float salary = 2;
      public boolean hasSalary() {
        return result.hasSalary();
      }
      public float getSalary() {
        return result.getSalary();
      }
      public Builder setSalary(float value) {
        result.hasSalary = true;
        result.salary_ = value;
        return this;
      }
      public Builder clearSalary() {
        result.hasSalary = false;
        result.salary_ = 0F;
        return this;
      }
      
      // required string position_name = 3;
      public boolean hasPositionName() {
        return result.hasPositionName();
      }
      public java.lang.String getPositionName() {
        return result.getPositionName();
      }
      public Builder setPositionName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPositionName = true;
        result.positionName_ = value;
        return this;
      }
      public Builder clearPositionName() {
        result.hasPositionName = false;
        result.positionName_ = "";
        return this;
      }
    }
    
    static {
      com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Worker_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Worker_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Worker_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Worker_Address_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Position_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\rexample.proto\022\010tutorial\"\315\002\n\006Worker\022\n\n\002" +
      "id\030\001 \002(\005\022\022\n\nname_first\030\002 \002(\t\022\023\n\013name_sec" +
      "ond\030\003 \002(\t\022\r\n\005phone\030\004 \001(\t\022%\n\tpositions\030\005 " +
      "\003(\0132\022.tutorial.Position\022.\n\014home_address\030" +
      "\006 \001(\0132\030.tutorial.Worker.Address\022.\n\014work_" +
      "address\030\007 \001(\0132\030.tutorial.Worker.Address\032" +
      "x\n\007Address\022\022\n\npost_index\030\001 \002(\005\022\014\n\004city\030\002" +
      " \002(\t\022\016\n\006street\030\003 \002(\t\022\020\n\010b_number\030\004 \002(\005\022\024" +
      "\n\014b_number_add\030\005 \001(\t\022\023\n\013flat_number\030\006 \001(" +
      "\005\"=\n\010Position\022\n\n\002id\030\001 \002(\005\022\016\n\006salary\030\002 \002(" +
      "\002\022\025\n\rposition_name\030\003 \002(\tB9\n(com.cherkash" +
      "yn.vitaliy.protobuf.exchangeB\rElementWor" +
      "ker";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Worker_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Worker_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Worker_descriptor,
              new java.lang.String[] { "Id", "NameFirst", "NameSecond", "Phone", "Positions", "HomeAddress", "WorkAddress", },
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.class,
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Builder.class);
          internal_static_tutorial_Worker_Address_descriptor =
            internal_static_tutorial_Worker_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Worker_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Worker_Address_descriptor,
              new java.lang.String[] { "PostIndex", "City", "Street", "BNumber", "BNumberAdd", "FlatNumber", },
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.class,
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Worker.Address.Builder.class);
          internal_static_tutorial_Position_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Position_descriptor,
              new java.lang.String[] { "Id", "Salary", "PositionName", },
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.class,
              com.cherkashyn.vitaliy.protobuf.exchange.ElementWorker.Position.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
