import java.io.IOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("- begin -");
        Files.walkFileTree(Paths.get("/tmp/temp-01/"), new SimpleFileVisitor<Path>() {
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                System.out.println(file);
                // Files.delete(file); - when another process will remove this file,
                // Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/temp-01/3.txt
                // will appear on Linux only !!!
                return FileVisitResult.CONTINUE; // super.visitFile(file, attrs);
            }
        });
        System.out.println("-  end  -");
    }

}


