
/**
* Env.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Env.idl
* четвер, 14 лютого 2008 р. 18:48:20 EET
*/

public interface Env extends EnvOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Env
