package test.database;

// Generated 23.06.2011 21:40:40 by Hibernate Tools 3.4.0.CR1

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	private Integer id;
	private String dictionaryName;
	private int keyId;
	private String keyValue;

	public Dictionary() {
	}

	public Dictionary(String dictionaryName, int keyId, String keyValue) {
		this.dictionaryName = dictionaryName;
		this.keyId = keyId;
		this.keyValue = keyValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDictionaryName() {
		return this.dictionaryName;
	}

	public void setDictionaryName(String dictionaryName) {
		this.dictionaryName = dictionaryName;
	}

	public int getKeyId() {
		return this.keyId;
	}

	public void setKeyId(int keyId) {
		this.keyId = keyId;
	}

	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

}
