import org.apache.commons.lang3.SystemUtils;
import org.zeroturnaround.exec.ProcessExecutor;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class KillProcess {

    public static void main(String ... args) throws InterruptedException, TimeoutException, IOException {
        if(args.length<1){
            System.out.println("specify number of the process");
            System.exit(1);
        }
        int pid = Integer.parseInt(args[0]);
        killProcess(pid);
    }

    public static void killProcess(int pid) throws InterruptedException, IOException, TimeoutException {
        if(SystemUtils.IS_OS_LINUX){
            killProcessLinux(pid);
        }
        if(SystemUtils.IS_OS_WINDOWS){
            killProcessWindows(pid);
        }
    }

    private static void killProcessWindows(int pid) throws InterruptedException, TimeoutException, IOException {
        new ProcessExecutor().commandSplit( String.format("Taskkill /pid %d /F", pid)).execute();
    }

    private static void killProcessLinux(int pid) throws InterruptedException, TimeoutException, IOException {
        new ProcessExecutor().commandSplit( String.format("kill -9 %d ", pid)).execute();
    }

}
