import sun.java2d.loops.ProcessPath;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("Press any key to continue");
        System.in.read();
        System.out.println("finished");
    }

}
