
/**
* EnvPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Env.idl
* четвер, 14 лютого 2008 р. 19:03:35 EET
*/

public abstract class EnvPOA extends org.omg.PortableServer.Servant
 implements EnvOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getenv", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Env/getenv
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.getenv (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Env:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Env _this() 
  {
    return EnvHelper.narrow(
    super._this_object());
  }

  public Env _this(org.omg.CORBA.ORB orb) 
  {
    return EnvHelper.narrow(
    super._this_object(orb));
  }


} // class EnvPOA
