/*******************************************************************************
 * Copyright 2009, Clark N. Hobbie
 * 
 * This file is part of the CLIPC library.
 * 
 * The CLIPC library is free software; you can redistribute it and/or modify it
 * under the terms of the Lesser GNU General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 * 
 * The CLIPC library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the Lesser GNU General Public
 * License for more details.
 * 
 * You should have received a copy of the Lesser GNU General Public License
 * along with the CLIP library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 * 
 *******************************************************************************/
package com.lts.ipc;

/**
 * A problem occurred while trying to use an IPC mechanism.
 *
 * <P>
 * This class allows clients to distinguish between exceptions generated by the classes
 * in this package and exceptions from other sources.  The exact nature of the exception
 * should be denoted by the message, which should be taken from one of the constants 
 * defined in the {@link Messages} class.
 * 
 * @author cnh
 */
@SuppressWarnings("serial")
public class IPCException extends Exception
{
	public IPCException (String msg)
	{
		super(msg);
	}
	
	public IPCException (String msg, Throwable cause)
	{
		super(msg, cause);
	}
}
