/*
 * JFrame_main.java
 *
 * Created on 7 Ноябрь 2007 г., 7:06
 */

package list_example;

import java.awt.Color;
import java.util.Vector;
import javax.swing.event.ListDataListener;

/**
 *
 * @author  root
 */
public class JFrame_main extends javax.swing.JFrame {
    public int jlist_counter=0;
    /** Creates new form JFrame_main */
    public JFrame_main() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Simple");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Create DefaultListModel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Create User List Model");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Create SelectionModel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("set Selection Color");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Create Incognito ListModel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(5, 5, 5)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // создать новый объект listmodel
        javax.swing.ListModel listmodel=new javax.swing.AbstractListModel() {
            String[] values=new String[10];
            //javax.swing.JCheckBox[] array_of_checkbox=new javax.swing.JCheckBox[10];
            {for(int i=0;i<values.length;i++){
                values[i]="elements "+i;
                //array_of_checkbox[i]=new javax.swing.JCheckBox(values[i]);
            };
            
            }
            public Object getElementAt(int index) {
                return values[index];
            };
            public int getSize() {
                return values.length;
            };
        };
        // установить в объект JList объект listmodel
        this.jList1.setModel(listmodel);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        javax.swing.ListModel listmodel=this.jList1.getModel();
        javax.swing.ListSelectionModel listselectionmodel=this.jList1.getSelectionModel();
        javax.swing.DefaultListCellRenderer defaultlistcellrenderer=new javax.swing.DefaultListCellRenderer();
        System.out.println("model created, length selection:"+this.jList1.getSelectedIndices().length);
        // получить список выделенных объектов
        jList1.setSelectionBackground(Color.gray);
        for(int i=0;i<this.jList1.getSelectedIndices().length;i++){
            System.out.println(i+" : "+listmodel.getElementAt( this.jList1.getSelectedIndices()[i] ));
            defaultlistcellrenderer.getListCellRendererComponent(this.jList1,this.jList1.getModel().getElementAt(this.jList1.getSelectedIndices()[i]),this.jList1.getSelectedIndices()[i],true,true).setBackground(Color.red);
        }
        
        this.jList1.setCellRenderer(defaultlistcellrenderer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        javax.swing.DefaultListSelectionModel defaultlistselectionmodel=new javax.swing.DefaultListSelectionModel();
        defaultlistselectionmodel.clearSelection();
        defaultlistselectionmodel.addSelectionInterval(1,1);
        defaultlistselectionmodel.addSelectionInterval(3,5);
        defaultlistselectionmodel.addSelectionInterval(8,9);
        this.jList1.setSelectionModel(defaultlistselectionmodel);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        javax.swing.ListModel listmodel=new javax.swing.ListModel() {
            public void addListDataListener(ListDataListener l) {
            }
            public Object getElementAt(int index) {
                String title="element:"+(index);
                javax.swing.JCheckBox checkbox=new javax.swing.JCheckBox(title);
                return checkbox;
            }
            public int getSize() {
                return 4;
            }
            public void removeListDataListener(ListDataListener l) {
            }
        };
        this.jList1.setModel(listmodel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        System.out.println("jList1 key pressed:"+evt.getKeyCode());
    }//GEN-LAST:event_jList1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // изменяем ListModel, но слушатели событий реально остаются
        javax.swing.DefaultListModel defaultlistmodel=new javax.swing.DefaultListModel();
        defaultlistmodel.addElement("new element:"+(++this.jlist_counter));
        defaultlistmodel.addElement("new element:"+(++this.jlist_counter));
        this.jList1.setModel(defaultlistmodel);
        // обновление вида элемента в соответствии с его моделью
        this.jList1.validate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // наполнить список новыми значениями
           // создать контейнер для наполнения
        Vector vector=new Vector();
           // наполнить контейнер
        for(int i=0;i<10;i++){
            vector.add("element: "+new Integer(i));
        }
           // установить новые данные
        this.jList1.setListData(vector);
           // установить выделение элементов
        this.jList1.setSelectionInterval(2,4);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
